### ISSUE TITLE
Code paths for already connected network resolve promise multiple times

### ISSUE THREAD

**Issue by teodorrd27** [JuanSeBestia/react-native-wifi-reborn#100]
There is an issue on iOS with attempting connection to an already connected network. Here's the blob.

https://github.com/JuanSeBestia/react-native-wifi-reborn/blob/4f76b75489034d0fa70bc3ccc8e44eed094db8da/ios/RNWifi.m#L109

I suggest returning after resolve or wrapping everything after in an else block. Otherwise you will get
'No callback found with cbID xxxx and callID xxx for WifiManager.connectToProtectedSSID - most likely the callback was already invoked.'

Thanks!

**Comment by eliaslecomte** [comment]
Can you make a pull request for it?

**Comment by teodorrd27** [comment]
Done, sorry for the closed request, I saw a better solution. Makes sense to reject the function call altogether. Otherwise for some reason `connectToProtectedSSID` would only work inside a try block.
Now we can call it neatly like this.
```
await WifiManager.connectToProtectedSSID('xxxxxxx', 'xxxxxx', false)
    .then(() => console.log('success'))
    .catch((reason: any) => console.log(reason))
```
#103

**Comment by Rapsssito** [comment]
Moved to PR #103
