### ISSUE TITLE
[Android] Connect to WiFi without internet access

### ISSUE THREAD

**Issue by arangu97** [JuanSeBestia/react-native-wifi-reborn#101]
Hi,

When I connect to my IoT device access point WiFi that has not access to the internet, my mobile phone gets disconnected from it after 5-10 seconds due to its lack of access to internet.

Is there any way to force this connection even there is no internet access? Because in my situation I need the communication between the app and the IoT device and no Internet access is needed.

If somebody has the same problem or know how to deal with it... I would appreciate it!

**Comment by eliaslecomte** [comment]
This is smartphone specific. Looks like letting the user connect, solves the problem. What smartphone models are giving you this problem?

**Comment by arangu97** [comment]
I dont think that is smartphone specific. I have tried with more than one brand(Xiaomi, Huawei...) and all have the Android 9 or 10 and in all of them this problem is happening. In some of them directly is not connecting whereas in others it connects but after 5-10 seconds it gets disconnected.

**Comment by cashc** [comment]
This function sounds like exactly what you're looking for. https://github.com/JuanSeBestia/react-native-wifi-reborn#forcewifiusageusewifi-boolean-promise

**Comment by arangu97** [comment]
I thought also that this function could solve my problem but after testing it the problem that I mentioned still persists.

There should be a way to do it because in the Google Home configuration app, it mantain the connection to the Google Home Wifi access point that has no internet access.

**Comment by PeterDwyer** [comment]
Android 10 uses a new wifi connection system. You will need to get the OS to create the connection and you will also need to set the connection settings so that you remove the requireswifi setting within the connection you create. This is some example code from a project I had to modify for the same reasons.
specifier = new Builder()
          .setSsid((String)ssidToConnect)
          .setWpa2Passphrase( password )
          .build();

networkRequest = new NetworkRequest.Builder()
                .addTransportType(NetworkCapabilities.TRANSPORT_WIFI)
                .removeCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
                .setNetworkSpecifier(specifier)
                .build();

Without the remove capability line the phone will either ask the user if they wish to continue on a connection without internet. If they say no (thinking there is a problem) then your app will never connect. The phone will also remember their prior choices.

Note this code is needed for android 10+ but, NOT for android 9 and below

**Comment by arangu97** [comment]
Ok, thank you.

So then, the React Native project must be ejected to native code in Android in order to use that functions right?

**Comment by cashc** [comment]
@arangu97 you're right, I couldn't get the forceWifiUsage function to work either. All requests were going through my cellular connection.

I ended up installing the npm package rn-fetch-blob and using the wifiOnly option to get the network requests to my IoT device to work. This approach might be easier if you're not comfortable with writing native android code.

**Comment by arangu97** [comment]
Thank you for your response. 

But in my case the problem is not when doing an HTTP request through a WiFi but just when connecting to the Wifi... After some seconds it disconnects from the wifi network without internet access. So I think that will no solve my problem :(

**Comment by eliaslecomte** [comment]
Is it because of intelligent wifi switching mechanism? There is an open PR: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/115 that might help. Do you have it on specific devices / os versions or all?

**Comment by arangu97** [comment]
Yes, thats it. 
The problem is not automatic switching between Wifi and Data Mobile but between 2 Wifi networks. 
I had this problem in some devices with Android 9+ version.
However, in other applications that use also some Wifi hotspot(without internet access) so as to configure a device (such as Google Home or other IoT devices) it is not disconnecting, so then there should be a way to force that the Wifi does not switch to a network with internet access.
I will have a look to that PR. 
Thanks.
