### ISSUE TITLE
[iOS] connectToProtectedSSIDPrefix display NEHotspotConfigurationError.userDenied

### ISSUE THREAD

**Issue by DrTerr** [JuanSeBestia/react-native-wifi-reborn#106]
If user denies a prompt when connectToProtectedSSIDPrefix is called, a generic error is raised, with only a localized message body to determine a error.

A error code must be attached to error properly 
`case userDenied = 7` as stated in
https://developer.apple.com/documentation/networkextension/nehotspotconfigurationerror/userdenied

So library user can determine and react accordingly if user have denied access to join.

Update to:
https://github.com/JuanSeBestia/react-native-wifi-reborn/blob/master/ios/RNWifi.m
is required to include a error code to allow library user to react properly.

Thanks

**Comment by eliaslecomte** [comment]
Hi, this is merged to master, should be released soon. Please help test / pr improvements if you can :-). One drawback is that not all iOS versions give the detailed error messages.

**Comment by DrTerr** [comment]
Hi, Ill be testing library soon.
One note, I don't actually want detailed message, just error code or Symbol/Field to know exact error types, without having to rely on parsing error message, which might get localized.
userDenied error code is most pressing, since it is fairly easy for user to deny access by accident. Other ones can be handled in more generic ways.

**Comment by DrTerr** [comment]
I checked PR, it seems to be exact things I wanted, ill be switching to new version as soon as possible.
