### ISSUE TITLE
Consider detaching this fork

### ISSUE THREAD

**Issue by kristfal** [JuanSeBestia/react-native-wifi-reborn#11]
Thanks for keeping this alive and moving forward!

The original repo is dead. To enable search and improved visibility on Github, I'd very much recommend that you detach this repo from the original one.

See https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository for details.

**Comment by JuanSeBestia** [comment]
Ok, it's consistent, I'll try to unlink it as you put it and I think I'll add the MIT license along the way

**Comment by Rapsssito** [comment]
Yay!

**Comment by JuanSeBestia** [comment]
I consider preserve the ISC licence to not vulnere the prev package

**Comment by JuanSeBestia** [comment]
Done!
