### ISSUE TITLE
Error: Cannot detect SSID in iOS

### ISSUE THREAD

**Issue by Shing-Ho** [JuanSeBestia/react-native-wifi-reborn#111]
I am getting `Error: Cannot detect SSID` error in iOS when I tried `WifiManager.getCurrentWifiSSID`.

"react-native": "0.63.2"
"react-native-wifi-reborn": "^4.2.2"

I installed the pod correctly and add Access Wifi Information and Hotspot Configuration capabilities.
Also, I added the `Privacy - Location When In Use Usage Description` and `Privacy - Location Always and When In Use Usage Description` in `Info.plist` and enable location in settings too.

**Comment by eliaslecomte** [comment]
Do you have more information like iphone model / emulator / iOS version?

**Comment by Shing-Ho** [comment]
iPhone model is iPhone6s 13.6
And I found it's not working in debug mode but working in release mode.

**Comment by eliaslecomte** [comment]
Yes, once you connect with a wifi network you loose connection with your packager / your app freezes.

**Comment by Shing-Ho** [comment]
So is there no way to work in debug mode?

**Comment by eliaslecomte** [comment]
Use Android 😉.
