### ISSUE TITLE
Enabling Wifi disables the Android hotspot (AP)

### ISSUE THREAD

**Issue by jdegger** [JuanSeBestia/react-native-wifi-reborn#118]
We are facing issues when an user is using their wifi hotspot and we try to enable the wifi. It seems to break their hotspot (AP).

I found the following code for reading if the hospot is in use: 

```java
WifiManager wifi = (WifiManager) getSystemService(Context.WIFI_SERVICE);
Method[] wmMethods = wifi.getClass().getDeclaredMethods();
for (Method method: wmMethods) {
  if (method.getName().equals("isWifiApEnabled")) {

    try {
      boolean isWifiAPenabled = method.invoke(wifi);
    } catch (IllegalArgumentException e) {
      e.printStackTrace();
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    } catch (InvocationTargetException e) {
      e.printStackTrace();
  }
}
```

I have not tested this, but wanted to discuss if it might be interesting to build in this feature into wifi-reborn.

I would propose to expose the AP status in a separate method so that we can decide if we want to check this before calling enable wifi.

**Comment by eliaslecomte** [comment]
I am not sure what to think of it. If you want to connect with a wifi network. This will inevitable stop the hotspot indeed.
This is the same if the user turns wifi on with a hotspot active.

Starting Android 10, you can no longer enable/disable wifi in code.

I think it would be interesting if you could test that code and verify on what versions it works?
You can easily add this code in a new NativeModule that you add in your project.

**Comment by jdegger** [comment]
Thanks for the quick response. I was not aware that it was not working anymore in Android 10. We have opted to remove the enable() method from our code altogether as it was not required for our use case.

Thanks
