### ISSUE TITLE
Failed resolution of: Lcom/thanosfisherman/elvis/Elvis

### ISSUE THREAD

**Issue by 1280103995** [JuanSeBestia/react-native-wifi-reborn#119]
![a7e3aa80-3a7e-47d5-ade1-a98ff11e3fd0](https://user-images.githubusercontent.com/17424486/93416076-99c98780-f8d7-11ea-9633-8583b0e9b795.png)

```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-wifi-reborn": "^4.3.0",
  },
```

**Comment by 1280103995** [comment]
I add 
```
implementation 'com.thanosfisherman.elvis:elvis:2.0'
``` 
in app/build.gradle, it work for me.

**Comment by stryaponoff** [comment]
There's a PR with fix waiting for accept https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/117
