### ISSUE TITLE
Android 10 Wifi issues

### ISSUE THREAD

**Issue by adnan1naeem** [JuanSeBestia/react-native-wifi-reborn#120]
I am facing issue in Android 10 that the device gets connected to the wifi but it is not throwing  internet though i ran google chrome but it was working fine but no internet access for my app. When i kill my app then internet starts supporting it .
I think there is an issue in which wifi is connected but not throwing internet. I am connecting to an Iot device then connecting back to  wifi which has an internet but still providing issue that there is no internet.

I have  also used  netinfo library which informs the network status but it provides connected false and  isInternetReachable:false 

Please help me in this case.

Thanks

**Comment by eliaslecomte** [comment]
Yes starting Android 10, only your app has internet access. Not for example chrome or other apps. Maybe I should add this to the readme.

**Comment by adnan1naeem** [comment]
> Yes starting Android 10, only your app has internet access. Not for example chrome or other apps. Maybe I should add this to the readme.

yes i am talking about my app  my react-native app does not have internet access even if wifi is connected

**Comment by adnan1naeem** [comment]
@eliaslecomte  can you please tell me how can i use ```forceWifiUsageWithOptions ``` in my code if there is no internet access

**Comment by arangu97** [comment]
I have also some problems with Android 10 and MIUI 12 operating system.

When using connecting to protected SSID it asks to allow this connection as seen in the below image: 

![image](https://user-images.githubusercontent.com/54932595/93993463-11dbf580-fd8f-11ea-9884-6f0590ae8ed0.png)

However when clicking the connect button this suddenly appears: 

![image](https://user-images.githubusercontent.com/54932595/93993525-24562f00-fd8f-11ea-8627-4d46a25aafb5.png)

After that, it does not appear anymore and connecting to Wifi is returning an error as seen in React Native console : 

 LOG      [Error: Could not connect to network]


I don't know if this is a OS problem, I will try my app with another Android or MIUI version.

**Comment by CKitisak** [comment]
I have the same dialog issue like @arangu97 posted.

**Comment by donzthefonz** [comment]
I'm experiencing the same thing, Android 10. 
With the popup asking "Device to use with...", it seems to be inconsistent.
Sometimes it:
- allows user to select the wifi, proceeds and succeeds.
- allows user to select the wifi, proceeds and says it failed but actually succeeded.
- auto selects the wifi for the user and succeeds.
- immediately fails.

**Comment by BroBan** [comment]
Same issue here, is this an issue that could be looked into? Thanks

**Comment by renanborgez** [comment]
Also facing the same problem

```
"react-native": "0.63.3",
"react-native-wifi-reborn": "^4.3.3",
```

Android 10
Huawei P20 Pro
EMUI 10.0.0

**Comment by CKitisak** [comment]
It works fine now for me on Android 10. I have added these permissions below in `AndroidManifest.xml`. 
After open the app I ask again the permission `ACCESS_FINE_LOCATION`

```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/> 
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
```

But I still got few errors as following sometimes:
![Selection_576](https://user-images.githubusercontent.com/2785185/98066581-0699e080-1e8a-11eb-8b93-de4a2bdcbf5c.png)

![Selection_575](https://user-images.githubusercontent.com/2785185/98066591-0bf72b00-1e8a-11eb-91ba-8b4e3dc3fcc5.png)

![Selection_574](https://user-images.githubusercontent.com/2785185/98066597-0f8ab200-1e8a-11eb-9520-08bc52d2ae10.png)

**Comment by MarcoStb1993** [comment]
I'm also unable to connect to a Wifi using my Samsung A40 with Android 10 and One UI version 2.0. The issue is the same as described by @donzthefonz .

The permissions @CKitisak proposed to add, did not fix the issue for me.

**Comment by CKitisak** [comment]
@MarcoStb1993 with Android 10 (based on my experience) on the first connect it will show the system UI. You have to select the SSID you needed to connect again on the system UI (only the first time. if you didn't select it, it will show the error). To solve that error you have to open the system UI and then forget that SSID.

**Comment by MarcoStb1993** [comment]
This solved it for me, thanks a lot @CKitisak!
