### ISSUE TITLE
Android crash  latest version 4.3.0

### ISSUE THREAD

**Issue by adnan1naeem** [JuanSeBestia/react-native-wifi-reborn#121]
I am using latest version of  the library but it is crashing with below error
<img width="1031" alt="Screenshot 2020-09-17 at 7 37 00 PM" src="https://user-images.githubusercontent.com/22443038/93486416-9a850c80-f91d-11ea-9215-c81fb7070968.png">

**Comment by stryaponoff** [comment]
https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/117
