### ISSUE TITLE
Android 10 - networkInfo inconsistencies

### ISSUE THREAD

**Issue by pherrera91** [JuanSeBestia/react-native-wifi-reborn#123]
Hello

I’m facing this issue https://github.com/react-native-community/react-native-netinfo/issues/411

Could it be something to be handled in this library?

**Comment by Rapsssito** [comment]
@pherrera91, I hope my comment can help you out. Moving the discussion over react-native-netinfo/react-native-netinfo#411 since it has more to do with react-native-netinfo, than with react-native-wifi-reborn.
