### ISSUE TITLE
Android 8 cannot scan or connect to WIFI

### ISSUE THREAD

**Issue by CKitisak** [JuanSeBestia/react-native-wifi-reborn#126]
Let say I have 4 android phones as following:

1. Samsung Galaxy S7 (Android 8)
2. Samsung Galaxy S8+ (Android 9)
3. Huawei P20 Pro (Android 10)
4. Samsung Galaxy S10+ (Android 10)

My *second*, *third*, and *forth* are working as expected (Scan and Connect) but the **first one** cannot scan or connect to the WIFI anymore. I have no idea why because I didn't get any error messages.

Please someone give me some advice.

I'm using `"react-native-wifi-reborn": "^4.3.1",`

Thank you

**Comment by Rapsssito** [comment]
@CKitisak, `connect()` does not work on Samsung Galaxy S7 (Android 8)?

**Comment by CKitisak** [comment]
sorry for late reply.
> @CKitisak, `connect()` does not work on Samsung Galaxy S7 (Android 8)?
it seem that `scan()` doesn't work so I cannot test `connect()`

**Comment by Rapsssito** [comment]
@CKitisak, my question is: is the issue is only happening on Samsung Galaxy S7 (Android 8)?

**Comment by CKitisak** [comment]
> @CKitisak, my question is: is the issue is only happening on Samsung Galaxy S7 (Android 8)?

correct

**Comment by Rapsssito** [comment]
@CKitisak could you check if the problem is related to scan() or connect ()?

**Comment by CKitisak** [comment]
> @CKitisak could you check if the problem is related to scan() or connect ()?

@Rapsssito  would you please guided me on how to check this on an Emulator because I don't have that phone just received the feedback from user and what they told me is they don't have any SSIDs on the list so I think it related to scan()?

**Comment by Rapsssito** [comment]
@CKitisak, if it is a problem with Android 8, you should be able to reproduce the issue with any emulator running Android 8. However, if it is not a problem with Android 8, it might be an issue with Samsung's firmware.

**Comment by CKitisak** [comment]
> @CKitisak, if it is a problem with Android 8, you should be able to reproduce the issue with any emulator running Android 8. However, if it is not a problem with Android 8, it might be an issue with Samsung's firmware.

I have tried on Android 8.0 and 8.1 emulator both shows the same result with the fake SSID called "AndroidWifi" and no error message.

**Comment by Rapsssito** [comment]
@CKitisak, does it work on the emulator with Android 9?

**Comment by CKitisak** [comment]
> @CKitisak, does it work on the emulator with Android 9?

I didn't test it yet but my phone is Andriod 9 and it works. but there just sometimes I have got the problem of `CouldNotScan` as I posted 
[here](https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/120#issuecomment-721494361)

**Comment by Rapsssito** [comment]
@CKitisak, could you test if the Android 8 problem is related to scanning networks or connecting to a network?

**Comment by eliaslecomte** [comment]
Hi,

The description of the errors is documented in the typescript declaration file (https://github.com/JuanSeBestia/react-native-wifi-reborn/blob/b867e70fb0ad5e445fba3fe4f30b5bc2189a9e65/lib/types/index.d.ts). Scanning for wifi networks is throttled. You might want to to get your hands on the real device. I am not sure if it's possible that the user enabled a setting that disables wifi scanning altogether.

**Comment by CKitisak** [comment]
thank you
