### ISSUE TITLE
WifiManager.forceWifiUsageWithOptions does not work

### ISSUE THREAD

**Issue by arangu97** [JuanSeBestia/react-native-wifi-reborn#128]
Hello,

I have tried the new functionality forceWifiUsageWithOptions for mantaining the connection with a Wifi with no internet but it is not working. I have tried this : 

WifiManager.forceWifiUsageWithOptions(true, {noInternet: true});

The app still changes my Wifi connection to other one that has Internet access.

**Comment by Rapsssito** [comment]
@arangu97, what react-native-wifi-reborn are you using? Are you using iOS or Android?

@eliaslecomte, this might be a bug over WifiUtils.

**Comment by arangu97** [comment]
The latest version of this library.
I am using it in Android, in a Pocophone.

**Comment by guiac** [comment]
Has anyone managed to use this function? forceWifiUsageWithOptions
