### ISSUE TITLE
Too many requests to give permissions to change the WiFi connectivity on Xiaomi devices.

### ISSUE THREAD

**Issue by ilyalezhnev** [JuanSeBestia/react-native-wifi-reborn#129]
Hi! I have problem with getting wi-fi permissions. There are many requests for wi-fi permissions from system on Xiaomi devices. Request for the permission for the wi-fi connection repeats itself several times after even a user mades their choice.

**Comment by Rapsssito** [comment]
@ilyalezhnev, it might be related to #79
