### ISSUE TITLE
Android disconnect() just returnstrue, but doesnt seem to disconnect from network?

### ISSUE THREAD

**Issue by digitlninja** [JuanSeBestia/react-native-wifi-reborn#131]
```
1.
 const disconnectFromNetwork = async (SSID: string) => {
            const currentSSID = await WifiManager.getCurrentWifiSSID();
            const isDisconnected = await WifiManager.isRemoveWifiNetwork(currentSSID);
            console.log({ currentSSID, isDisconnected });
        };
2.
   const disconnectFromNetwork = async (SSID: string) => {
            const isDisconnected = await WifiManager.disconnect();
            console.log({ isDisconnected });
        };
```

I've tried both of these, all I get is true, but the satellite icon is still on and it doesnt disconnect

**Comment by renanborgez** [comment]
same here

**Comment by renanborgez** [comment]
same here
"react-native": "0.63.3",
"react-native-wifi-reborn": "^4.3.2",

**Comment by diegoneg** [comment]
still verifying same problem on real android device:

"react-native": "0.63.2",
"react-native-wifi-reborn": "^4.3.2",

**Comment by Rapsssito** [comment]
@digitlninja check #34, it might be the same problem you are experiencing.

**Comment by ashu090990** [comment]
same issue

**Comment by ashu090990** [comment]
Any update ?

**Comment by LauraKipfel** [comment]
Same issue, any update ?

**Comment by eliaslecomte** [comment]
If I have some time I'll look into it. For Android, I would suggest using `isRemoveWifiNetwork` for now.

Questions:
* Can you reproduce on multiple phones?
* What phone model is used?
* What Android OS is used?
* Was the wifi network connected before via settings?

And also, in my experience, if you use the disconnect function, but there is no other wifi network arround, Android silently reconnect.

**Comment by LauraKipfel** [comment]
Work for me to use isRemoveWifiNetwork() on Android. Thanks !
