### ISSUE TITLE
WifiManager.isRemoveWifiNetwork(ssid) NullPointerException

### ISSUE THREAD

**Issue by 1280103995** [JuanSeBestia/react-native-wifi-reborn#135]
Hello!

I received an error message from Sentry：```Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference```

Log:
com.thanosfisherman.wifiutils.ConfigSecurities in getWifiConfiguration at line 171
com.thanosfisherman.wifiutils.ConnectorUtils in removeWifi at line 532
com.thanosfisherman.wifiutils.WifiUtils in remove at line 315
com.reactlibrary.rnwifi.RNWifiModule in isRemoveWifiNetwork at line 364

Device:  Galaxy S6(Android 7.0)

```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-wifi-reborn": "^4.3.0"
```

I don't have real device to test it. If it has been fixed in the next version, please close this issue. 
Thank you.

**Comment by Rapsssito** [comment]
@1280103995, could you provide a reproducible demo with the code that is causing the error?

**Comment by 1280103995** [comment]
Sorry! The simple code is like this:
```
import React from 'react';
import {Text} from 'react-native';
import WifiManager from 'react-native-wifi-reborn';
import {request,  PERMISSIONS, RESULTS} from 'react-native-permissions';

const App = () => {

  const requestLocationPermission = async() => {
    let hasPermission = false;
    await request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION).then(result => {
      if (result === RESULTS.GRANTED) {
        hasPermission = true;
      }
    });
    return hasPermission
  };

  const connect = async (ssid, password) => {
    WifiManager.isRemoveWifiNetwork(ssid);
    return new Promise((resolve, reject) => {
      WifiManager.connectToProtectedSSID(ssid, password, false).then(
        () => {
          console.log("Connected successfully!");
          resolve(true)
        },
        async(error) => {
          console.log("Connection failed!");
          if (error.toString().includes('Location permission (ACCESS_FINE_LOCATION) is not granted')) {
            const hasPermission = await requestLocationPermission();
            if (hasPermission) resolve(connect(ssid, password))
          }
          resolve(false)
        }
      );
    })
  };

  const _onPress = async() => {
    const isConnect = await connect('ssid123', 'password123')
    console.log("isConnected", isConnect);
  };

  return (
    <Text
      onPress={_onPress}
      style={{
        fontSize: 24,
        fontWeight: '600',
        color: 'black',
        padding: 50,
        textAlign: 'center',
      }}
    >
      Test
    </Text>
  );
};
export default App
```
```<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />```has been added to ```android/app/src/main/AndroidManifest.xml``` file.

**Comment by Rapsssito** [comment]
@1280103995, what line is causing the error?

**Comment by 1280103995** [comment]
@Rapsssito ```WifiManager.isRemoveWifiNetwork(ssid);```

May be caused by calling twice?

**Comment by Rapsssito** [comment]
@1280103995, it might actually be caused by you trying to remove a WiFi network added by the user. `isRemoveWifiNetwork()` can only remove WiFi SSIDs added by your app, not the user.

**Comment by 1280103995** [comment]
Hi, @Rapsssito, as you said, i can’t reproduce it on TECNO Phantom 9(Android 9).

I can only expect someone to test it.  ^_^

**Comment by nickyleach** [comment]
> It might actually be caused by you trying to remove a WiFi network added by the user. `isRemoveWifiNetwork()` can only remove WiFi SSIDs added by your app, not the user.

@Rapsssito I think I'm running into a similar problem (`isRemoveWifiNetwork()` throwing a NPE). Is there a way to determine if it's safe to call `isRemoveWifiNetwork()`?

**Comment by Rapsssito** [comment]
@nickyleach, since you can only use `isRemoveWifiNetwork()` if your app has added that WiFi, you must keep a list of all the WiFi networks added by your app in persistent storage in order to determine if it is safe to call `isRemoveWifiNetwork()`.

**Comment by stravi** [comment]
I had a similar issue. My app was crashing in the exact same spot. This was happenning only to Samsung S6, Huawei P20 and Samsung S7 had no issues. I have realised that it crashes only if the wifi network is not enabled
