### ISSUE TITLE
Possible issue in the documentation on github as well as on npmjs site

### ISSUE THREAD

**Issue by yashanand07** [JuanSeBestia/react-native-wifi-reborn#14]
Is this right? Or should it be **react-native-wifi-reborn**?

project(':react-native-wifi-reborn').projectDir = new File(rootProject.projectDir, 	'../node_modules/**react-native-wifi**/android')

The same documentation if need be needs to be changed on  [npmjs site](https://www.npmjs.com/package/react-native-wifi-reborn) as well

**Comment by JuanSeBestia** [comment]
Thanks for noticing, I've already committed it

**Comment by yashanand07** [comment]
Thanks Juan. I will also check IOS 13 patch by putting a hack into the original module. Hoping that you would release a new module for us to use as the original one is obselete due to no changes being taken up. Thanks from all of us.
