### ISSUE TITLE
RN fetch fails after successfully connecting and disconnecting with wifi

### ISSUE THREAD

**Issue by MarcoStb1993** [JuanSeBestia/react-native-wifi-reborn#140]
Hey,

I've experienced a weird issue that I narrowed down to this library. I am using a Samsung A40 with Android 10, RN 0.63.2 and version 4.3.3 of react-native-wifi-reborn.

In my app, I connect to a wifi provided by a sensor (a seismograph to be more specific) which is not connected to the internet, retrieve its measurements with fetch requests and then disconnect from its wifi again. This procedure is repeated over and over during a field day. In between measurements, the app uses mobile data to upload the measurements to a server (that is the reason for connecting and disconnecting again). As soon as mobile data is turned off briefly or the connection is lost and reestablished, all future fetch requests to the server fail with the below error message (which unfortunately provides no helpful information for me). Requests to the sensor when connected to its wifi still work. After shutting down and restarting the app, the fetch requests work again.

```
TypeError: Network request failed
    at C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\whatwg-fetch\dist\fetch.umd.js:527
    at C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:235
    at _callTimer (C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130)
    at Object.callTimers (C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:383)
    at MessageQueue.__callFunction (C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416)
    at C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109
    at MessageQueue.__guard (C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364)
    at MessageQueue.callFunctionReturnFlushedQueue (C:\Users\msteinbrink\WebstormProjects\seismic\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108)
    at debuggerWorker.cff11639.js:4
```

The data with headers to be uploaded when a fetch request fails was tested in Postman and worked without a problem. After disconnecting from the sensor's wifi, the WifiManager.connectionStatus() method returns false and NetInfo also shows the connection as connected to the internet via cellular.  

I also removed this package's dependency and tested the same workflow with manually connecting and disconnecting the wifi in which case future fetch requests work as expected. When using this package and briefly disconnecting mobile data without polling a sensor meanwhile, future fetch requests also work as expected. Only if mobile data is briefly disconnected and this package is used to connect and disconnect from the sensor's network, future fetch requests to the server always fail until the app is restarted.

Therefore, I suspect that using the WifiManager to connect and disconnect to the wifi without internet somehow breaks future fetch requests. Do you have any idea what could cause this problem and why restarting the app resets it?

I don't know if it is relevant, but fetch requests to the sensor are http and not https (like the requests to the server). Therefore, `android:usesCleartextTraffic="true"` was added to the *AndroidManifest.xml*.

Any help would be greatly appreciated!

**Comment by Rapsssito** [comment]
@MarcoStb1993, thanks for the extended explanation. Correct me if I am wrong, the issue is that after disconnecting to the WiFi without internet breaks future fetch requests. So fetch requests before disconnecting the first time work fine.
How are you sending those fetch requests?

**Comment by MarcoStb1993** [comment]
@Rapsssito, thank you for replying. Yes, exactly. After connecting and disconnecting to the sensor's hotspot (which has no internet connection), future fetch requests  to the server fail. It is possible to connect to the sensor again and fetch the measurements, only requests to the server (via mobile data) fail until the app is restarted.

My fetch requests to the server look like this:
```
const connectionString = database + table + filter;
  try {
    let response = await fetch(connectionString, {
      method: 'GET',
      headers: headers_,
    });
    if (response.ok) {
      WriteToLog('GET Request for ' + connectionString + ' successful', 'info');
      let json = await response.json();
      return {success: true, response: await json.value};
    } else {
      WriteToLog(
        'GET Request for ' + connectionString + ' not ok: ' + response.message,
        'warning',
      );
      return {success: false, response: undefined};
    }
  } catch (error) {
    WriteToLog(
      'GET Request for ' + connectionString + ' failed: ' + error,
      'error',
    );
    return {success: false, response: undefined};
  }
```

Where the header object looks like this:

```
const headers_ = {
  Accept: 'application/json',
  'Content-Type': 'application/json',
  Authorization: 'Basic example123', 
};
```

Requests to the sensor are similar except that the connection string is different.

**Comment by Rapsssito** [comment]
@MarcoStb1993 are you using any kind of timeout between connecting to the hotspot WiFi and sending the fetch request?

**Comment by MarcoStb1993** [comment]
No, I don't. But I use `await` syntax for connecting and disconnecting. So, only when the connect function is finished, a fetch-request will be sent. The same goes for disconnecting (even though the disconnect function always just returns `true`).

**Comment by Rapsssito** [comment]
@MarcoStb1993 could you try using react-native-netinfo and post your WiFi state just before you send the fetch request? Here is an example code:
```js
import NetInfo from '@react-native-community/netinfo';

const networkInfo = await NetInfo.fetch('wifi');
console.log(networkInfo);
```

**Comment by MarcoStb1993** [comment]
@Rapsssito Unfortunately, I currently don't have a sensor for testing.

But I previously used NetInfo to check the connection because I suspected that the Wifi was not correctly disconnected. But according to NetInfo it was disconnected. Directly after connecting to the hotspot it showed `type: wifi` and `isInternetReachable: false`. After disconnecting it immediately showed `type: cellular` and `isInternetReachable: true`.

**Comment by Rapsssito** [comment]
@MarcoStb1993, do you remember what NetInfo showed after you tried to connect to the WiFi again and the fetch requests failed?

**Comment by MarcoStb1993** [comment]
@Rapsssito As far as I recall, NetInfo was always showing the seemingly correct status. `type: wifi` and `isInternetReachable: false` when connected to the hotspot and `type: cellular` and `isInternetReachable: true` when disconnected from the hotspot.

Just to clarify: The fetch requests sent to the sensor when connected to its hotspot always succeed. Only the requests sent to the server after disconnecting from the sensor's hotspot fail. This remains the same after connecting to and disconnecting from the hotspot multiple times.

**Comment by Rapsssito** [comment]
@MarcoStb1993, sorry I think I didn't understand your issue before. Your **cellular** fetch requests fail are the ones that are failing?

**Comment by MarcoStb1993** [comment]
@Rapsssito Yes, exactly. At first cellular requests work, then I use this package to connect to the sensor's hotspot without internet and do fetch requests to the sensor via wifi, they work as well. But after I disconnect from the hotspot, all cellular fetch requests fail until I restart the app.

**Comment by Rapsssito** [comment]
@MarcoStb1993 have to tried with `isRemoveWifiNetwork()`?

**Comment by MarcoStb1993** [comment]
@Rapsssito I think I didn't. I hope I can try it next week, and will update this as soon as I did. Thank you for your help so far!

**Comment by eliaslecomte** [comment]
Hey @MarcoStb1993. Are you using forceWifiUsage or forceWifiUsageWithOptions?
It's importantant to unforce it after executing your api call to the device:
`await forceWifiUsageWithOptions(false, { noInternet: true });`

**Comment by MarcoStb1993** [comment]
Hi @eliaslecomte. No, I'm using neither. Do you mean I should use the forceWifiUsage method for my application? If so, thank you for your suggestion, I will try next week! :)

This is how I call this package's methods:

```
export async function ConnectToSensorWifi() {
  try {
    await WifiManager.setEnabled(true);
    await WifiManager.connectToProtectedSSID(
      _wifiPrefix + store.getState().sensorId,
      _wifiPassword,
      false,
    );
  } catch (error) {
    console.log(error);
  }
}

export async function DisconnectFromSensorWifi() {
  try {
    if (Platform.OS === 'ios') {
      await WifiManager.disconnectFromSSID(
        _wifiPrefix + store.getState().sensorId,
      );
    } else {
      await WifiManager.disconnect();
    }
  } catch (error) {
    WriteToLog('Disconnected from SensorWifi failed', 'error');
  } finally {
    WriteToLog('Disconnected from Sensor Wifi', 'info');
  }
}
```

**Comment by MarcoStb1993** [comment]
@eliaslecomte I just tried it with your advice and it worked! Thank you and @Rapsssito for your help.

I added the following after connecting to the sensor's wifi on Android:

```
await WifiManager.forceWifiUsageWithOptions(true, {noInternet: true});
```

And this after disconnecting from the sensor:
```
await WifiManager.forceWifiUsageWithOptions(false, {noInternet: true});
```

**Comment by eliaslecomte** [comment]
Super! You think we should update the readme so this is more clear?

**Comment by MarcoStb1993** [comment]
@eliaslecomte Maybe a small hint at the start. To be honest, if I would've read the readme completely, this wouldn't have happened. So, I guess its on me and not on an unclear readme.

**Comment by stravi** [comment]
> And this after disconnecting from the sensor:
> 
> ```
> await WifiManager.forceWifiUsageWithOptions(false, {noInternet: true});
> ```

What if you have forced WiFi usage without internet when you App connected to the sensor. But then user disconnects from your sensor WiFi network manually by going to Settings -> WiFi. Per [this](https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/140#issuecomment-742453537) comment, it means the user won't be able to use phone data afterwards. If this is true, how would you solve this issue?
