### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by rhdtl78** [JuanSeBestia/react-native-wifi-reborn#142]
Environments
- "react": "16.13.1",
- "react-native": "0.63.3",
- "react-native-wifi-reborn": "^4.3.3",

Description
- When I call connectToProtectedSSID(), app was crashed with error that elvis class not found.

And I manually add the dependency to react-native-wifi-reborn
> implementation 'com.thanosfisherman.elvis:elvis:3.0'

after that, it work correctly.

**Comment by AnagramEngineering** [comment]
I see the same problem, but only on production build. Development builds are working fine.

**Comment by iralution** [comment]
Same for me, tested with Android 9 and 11

**Comment by DennisOstertag** [comment]
Same error, some error logs here:

```
com.thanosfisherman.wifiutils.WifiUtils$1.onWifiEnabled
java.lang.ClassNotFoundException: com.thanosfisherman.elvis.Elvis

com.thanosfisherman.wifiutils.WifiUtils$1.onWifiEnabled
WifiUtils.java, line 106
java.lang.ClassNotFoundException: Didn't find class "com.thanosfisherman.elvis.Elvis" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/<APP>==/base.apk"],nativeLibraryDirectories=[/data/app/<APP>==/lib/arm64, /data/app/<APP>==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]

```

I will try to add the dependency manually and report back if that fixed the error.

**Comment by AnagramEngineering** [comment]
as @rhdtl78 has mentioned, adding the dependency manually solves the problem

**Comment by longnk1301** [comment]
please create PR

**Comment by jeremiahogutu** [comment]
![Screenshot_20201204-151519_Grobo.jpg](https://user-images.githubusercontent.com/28146531/101226845-c9309a80-3663-11eb-8bf4-f787bc5e96d7.jpg)

**Comment by jeremiahogutu** [comment]
I can confirm that adding dependency fixes this.

**Comment by Rapsssito** [comment]
@eliaslecomte, is this an issue with this library or WifiUtils?

**Comment by nashvent** [comment]
I also confirm that manually adding the dependency solves the problem.
In android/app/build.gradle
`implementation 'com.thanosfisherman.elvis:elvis:3.0'`

**Comment by eliaslecomte** [comment]
Ow I didn't see this before. As elvis is a dependency of WifiUtils, it's an issue that has to be solved in WifiUtils.
