### ISSUE TITLE
Once connected to a Wifi, i cannot navigate with browser

### ISSUE THREAD

**Issue by M9lab** [JuanSeBestia/react-native-wifi-reborn#143]
"react-native": "^0.63.2",
"react-native-wifi-reborn": "^4.3.3",

Hello, i follow the main example to connect a hotspot, after successfully connected i cannot navigate via browser. 
(still offline) until i close my app or restart it

**Comment by M9lab** [comment]
Yes starting Android 10, only your app has internet access. Not for example chrome or other apps. Maybe I should add this to the readme.

**Comment by aelhani** [comment]
Hi,

I'd like to have internet available to all apps in my phone after connecting to a wifi.
Is there a way to bypass this limitation "only app has internet access" ?

Also, could you please provide some useful links to learn further about this.

Thank you
