### ISSUE TITLE
Is it possible to prevent a wifi scan before connect?

### ISSUE THREAD

**Issue by CKitisak** [JuanSeBestia/react-native-wifi-reborn#144]
let say I have an app which already done a scan process (call `reScanAndLoadWifiList()`) and show a list of WIFIs. when users select any WIFI then the app call `connectToProtectedSSID` with the selected SSID and the PSK (if needed) and sometimes the `couldNotScan` error immediately occured. is there an option or the way to avoid this error?

**Comment by guiac** [comment]
I have the same problem. Did you manage to solve? Can you help me? thanks in advance

**Comment by CKitisak** [comment]
I'm using just a `loadWifiList()` now and add a button call REFRESH for user to do a manual `reScanAndLoadWifiList()` with some interval to avoid reaching 4 times within 2 minutes.

**Comment by guiac** [comment]
Nice! But can you tell me if the connectToProtectedSSID function checks the network?

**Comment by guiac** [comment]
Nice! But can you tell me if the connectToProtectedSSID function scans the network?

**Comment by CKitisak** [comment]
> Nice! But can you tell me if the connectToProtectedSSID function scans the network?

I don't know how to check exactly but I guess yes because if you did 4 times rescan then when you connect to the ssid it will return `couldNotScan` error.

**Comment by eliaslecomte** [comment]
This isn't implemented but is possible to do. Are you an Android dev, can you take it up?
