### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by JuanSeBestia** [JuanSeBestia/react-native-wifi-reborn#15]
I'm considering adding typing for TypeScript which is the one I use the most,

**Comment by stanpak** [comment]
Yes please. I ran into the issues while using newest react-native with your library. It complains that the .d.ts file is not found. I created one (index.d.ts) with single line "declare module 'react-native-wifi-reborn';" but it still generates error messages that let say "method isEnabled is undefined" or in that sort. So it looks like the system expects more meaningful content in this file.

**Comment by JuanSeBestia** [comment]
You would need declare like this https://stackoverflow.com/questions/31729668/how-to-declare-any-module-in-typescript.

But yes, it coming soon

**Comment by thibmaek** [comment]
Feel free to look here: https://github.com/inthepocket/react-native-wifi-reborn/blob/master/index.d.ts

We forked this lib to our TS codebase because upstream repo wasn't working for our application and added TS support along the way.

**Comment by Rapsssito** [comment]
@thibmaek, thanks! We'll take a look at it.

**Comment by thibmaek** [comment]
Let me know if I can help out with this.
