### ISSUE TITLE
Build failed for Android, when the version target 4.3.5 or 4.3.6

### ISSUE THREAD

**Issue by mickeylam** [JuanSeBestia/react-native-wifi-reborn#153]
"react-native": "0.61.2",
 "react-native-wifi-reborn": "^4.3.3",
 
 When I set to 4.3.3, the build is successful.

 Error:
 > Task :react-native-wifi-reborn:generateDebugBuildConfig
1756 > Task :react-native-wifi-reborn:javaPreCompileDebug
1757 > Task :react-native-wifi-reborn:compileDebugJavaWithJavac FAILED
1758 /builds/mobile/universal-app/node_modules/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java:27: error: cannot find symbol
1759 import com.reactlibrary.rnwifi.errors.GetCurrentWifiSSIDErrorCodes;
1760                                      ^
1761   symbol:   class GetCurrentWifiSSIDErrorCodes
1762   location: package com.reactlibrary.rnwifi.errors
1763 /builds/mobile/universal-app/node_modules/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java:310: error: package GetCurrentWifiSSIDErrorCodes does not exist
1764             promise.reject(GetCurrentWifiSSIDErrorCodes.CouldNotDetectSSID.toString(), "Not connected or connecting.");
1765                                                        ^
1766 Note: Some input files use or override a deprecated API.
1767 Note: Recompile with -Xlint:deprecation for details.
1768 2 errors
1769 FAILURE: Build failed with an exception.
1770 * What went wrong:
1771 Execution failed for task ':react-native-wifi-reborn:compileDebugJavaWithJavac'.
1772 > Compilation failed; see the compiler error output for details.

**Comment by ujjwalsayami** [comment]
I'm having trouble using latest version as well. 
"react-native-wifi-reborn": "^4.3.6"

**Comment by xralphack** [comment]
4.3.5 can pass, 4.3.6 can not

**Comment by lucaguazzaroni** [comment]
Hi, Similar issue here.

```sh
info Installing the app...

> Task :react-native-wifi-reborn:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
72 actionable tasks: 2 executed, 70 up-to-date
C:\Users\Latitude E7440\Documents\React-Native\lightControlApp\node_modules\react-native-wifi-reborn\android\src\main\java\com\reactlibrary\rnwifi\RNWifiModule.java:27: error: cannot find symbol
import com.reactlibrary.rnwifi.errors.GetCurrentWifiSSIDErrorCodes;
                                     ^
  symbol:   class GetCurrentWifiSSIDErrorCodes
  location: package com.reactlibrary.rnwifi.errors
C:\Users\Latitude E7440\Documents\React-Native\lightControlApp\node_modules\react-native-wifi-reborn\android\src\main\java\com\reactlibrary\rnwifi\RNWifiModule.java:310: error: package GetCurrentWifiSSIDErrorCodes does not exist
            promise.reject(GetCurrentWifiSSIDErrorCodes.CouldNotDetectSSID.toString(), "Not connected or connecting.");
                                                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-wifi-reborn:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

My enviroment is

- react-native 0.63.4
- react-native-wifi-reborn 4.3.6
- gradle 6.7

**Comment by Satyam-code143** [comment]
@lucaguazzaroni 

Did you get any solution for this??
I am getting the same problem.

**Comment by ujjwalsayami** [comment]
@Satyam-code143  You can use version  "react-native-wifi-reborn": "4.3.5"

**Comment by Satyam-code143** [comment]
Hey, @ujjwalsayami  thank you for your response. I tried installing 4.3.5 version but now I am getting a new error.

`> Task :app:processDebugManifest FAILED `.

**Comment by crazypioneer** [comment]
https://stackoverflow.com/questions/65695566/task-react-native-wifi-reborncompiledebugjavawithjavac-failed-react-native/65698397#65698397


Check here.

**Comment by ujjwalsayami** [comment]
@Satyam-code143 can you post your full error

**Comment by Satyam-code143** [comment]
@ujjwalsayami  Here is my error:

`> Task :react-native-wifi-reborn:compileDebugJavaWithJavac FAILED `

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.                             Use '--warning-mode all' to show the individual deprecation warnings.                                                   See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings                         122 actionable tasks: 2 executed, 120 up-to-date                                                                        G:\MIOTICS\HomeAutomation\node_modules\react-native-wifi-reborn\android\src\main\java\com\reactlibrary\rnwifi\RNWifiModule.java:27: error: cannot find symbol                                                                                   import com.reactlibrary.rnwifi.errors.GetCurrentWifiSSIDErrorCodes;                                                                                          ^                                                                                    symbol:   class GetCurrentWifiSSIDErrorCodes                                                                            location: package com.reactlibrary.rnwifi.errors                                                                      G:\MIOTICS\HomeAutomation\node_modules\react-native-wifi-reborn\android\src\main\java\com\reactlibrary\rnwifi\RNWifiModule.java:310: error: package GetCurrentWifiSSIDErrorCodes does not exist                                                             promise.reject(GetCurrentWifiSSIDErrorCodes.CouldNotDetectSSID.toString(), "Not connected or connecting.");                                                        ^                                                                Note: Some input files use or override a deprecated API.                                                                Note: Recompile with -Xlint:deprecation for details.                                                                    2 errors                                                                                                                                                                                                                                        FAILURE: Build failed with an exception.                                                                                                                                                                                                        * What went wrong:                                                                                                      Execution failed for task ':react-native-wifi-reborn:compileDebugJavaWithJavac'.                                        > Compilation failed; see the compiler error output for details.                                                                                                                                                                                * Try:                                                                                                                  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.                                                                                                                                                                                                                    * Get more help at https://help.gradle.org                                                                                                                                                                                                      BUILD FAILED in 45s `

**Comment by lucaguazzaroni** [comment]
> 
> 
> @lucaguazzaroni
> 
> Did you get any solution for this??
> I am getting the same problem.

Hi! The problem was that GetCurrentWifiSSIDErrorCodes was a Kotlin file.

The solution:

1. Go to /node_module/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/erros

2. Change the extension of GetCurrentWifiSSIDErrorCodes.kt to GetCurrentWifiSSIDErrorCodes.java. And then
    change the file content for this
```java
package com.reactlibrary.rnwifi.errors;

public enum GetCurrentWifiSSIDErrorCodes {
    /**
     * Not connected or connecting.
     */
    CouldNotDetectSSID,
}
```

**Comment by Satyam-code143** [comment]
@lucaguazzaroni  

> 
> 
> > @lucaguazzaroni
> > Did you get any solution for this??
> > I am getting the same problem.
> 
> @Satyam-code143
> 
> Hi! The problem was that GetCurrentWifiSSIDErrorCodes was a Kotlin file.
> 
> The solution:
> 
>     1. Go to /node_module/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/erros
> 
>     2. Change the extension of GetCurrentWifiSSIDErrorCodes.kt to GetCurrentWifiSSIDErrorCodes.java. And then
>        change the file content for this
> 
> 
> ```java
> package com.reactlibrary.rnwifi.errors;
> 
> public enum GetCurrentWifiSSIDErrorCodes {
>     /**
>      * Not connected or connecting.
>      */
>     CouldNotDetectSSID,
> }
> ```
> 
>     1. Run again
> 
> 
> ```shell
> npx react-native run-android
> ```


Hey! I tried this but I go this error!!

`> Task :app:processDebugManifest FAILED `

**Comment by lucaguazzaroni** [comment]
> 
> 
> @lucaguazzaroni
> 
> > > @lucaguazzaroni
> > > Did you get any solution for this??
> > > I am getting the same problem.
> > 
> > 
> > @Satyam-code143
> > Hi! The problem was that GetCurrentWifiSSIDErrorCodes was a Kotlin file.
> > The solution:
> > ```
> > 1. Go to /node_module/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/erros
> > 
> > 2. Change the extension of GetCurrentWifiSSIDErrorCodes.kt to GetCurrentWifiSSIDErrorCodes.java. And then
> >    change the file content for this
> > ```
> > 
> > 
> > ```java
> > package com.reactlibrary.rnwifi.errors;
> > 
> > public enum GetCurrentWifiSSIDErrorCodes {
> >     /**
> >      * Not connected or connecting.
> >      */
> >     CouldNotDetectSSID,
> > }
> > ```
> > 
> > 
> > ```
> > 1. Run again
> > ```
> > 
> > 
> > ```shell
> > npx react-native run-android
> > ```
> 
> Hey! I tried this but I got this error!!
> 
> `> Task :app:processDebugManifest FAILED `
> 
> ![MainProblem](https://user-images.githubusercontent.com/56146542/104465946-a25a7200-55da-11eb-99ef-67066be6f7be.JPG)

Maybe if you try with 4.3.6 version? In the comment you made above this error showed up when you changed to 4.3.5 version.

**Comment by Satyam-code143** [comment]
@lucaguazzaroni 

No the error comes for both the versions

**Comment by Satyam-code143** [comment]
@lucaguazzaroni  
Hey!! Thank You very much!!

Your answer helped a lot. I did get the above mentioned Error. `> Task :app:processDebugManifest FAILED ` I did find solution for that. My `minSdkVersion` was lower, it was `16` and was asking for `21`. I made the changes in `build.gradle`. The [ref link](https://github.com/wmcmahan/react-native-calendar-events/issues/213#issuecomment-461852948) for the same.

@ujjwalsayami  and @crazypioneer  thank you for your help.

**Comment by eliaslecomte** [comment]
Looks like I was to enthusiastic on using kotlin mixed with java. Let me fix this.

**Comment by Asharuddin-90** [comment]
I am getting build failed previously I was using version 4.7.0 and it was working fine but now when I upgrade it to 4.10.1(latest)

Then I facing issue while building debug 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/viraj/Desktop/Qqueridoo/qeridoo-app/node_modules/react-native-wifi-reborn/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':react-native-wifi-reborn'.
> Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-wifi-reborn'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s


can someone help me?

**Comment by lukiinhas1616** [comment]
@Asharuddin-90 any update to this issue?
