### ISSUE TITLE
IsRemoveWifiNetwork does not exist for iOS

### ISSUE THREAD

**Issue by scarlac** [JuanSeBestia/react-native-wifi-reborn#155]
`IsRemoveWifiNetwork` does not exist for iOS. This isn't documented and isn't clear from the typescript definition.

Could we either:
- Update README.md to say that it's android only? or...
- Add iOS support?

(on a side note, maybe the name should be changed to `removeWifiNetwork` - ie. removing the leading "is")

**Comment by eliaslecomte** [comment]
The method is listed in the readme under [Only Android](https://github.com/JuanSeBestia/react-native-wifi-reborn#only-android).

**Comment by scarlac** [comment]
Sorry, I completely missed the section title. Closing.

**Comment by eliaslecomte** [comment]
You are not the first, maybe we should add an ios - android label after every method 🤔.
