### ISSUE TITLE
Support for Android 11?

### ISSUE THREAD

**Issue by MattBlanco** [JuanSeBestia/react-native-wifi-reborn#157]
Has anyone gotten this to work with Android 11?

I'm trying to connect to a protected IoT network that doesn't connect to the internet through my app, but it says that the connection is low quality and then automatically disconnects on my pixel 5. But if I connect to the network through my wifi settings, it stays connected.

Here's what I'm trying:

> ConnectToNetwork = useCallback(async () => {
>       WifiManager.setEnabled(true);
>       const granted = await PermissionsAndroid.request(
>         PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
>         {
>           title: 'Location permission is required for WiFi connections',
>           message:
>             'This app needs location permission as this is required  ' +
>             'to scan for wifi networks.',
>           buttonNegative: 'DENY',
>           buttonPositive: 'ALLOW',
>         },
>       );
>       if (granted === PermissionsAndroid.RESULTS.GRANTED) {
>         WifiManager.connectToProtectedSSID("NetworkName", "valqari123", false)
>           .then(
>             () => {
>               WifiManager.forceWifiUsageWithOptions(true, { noInternet: true })
>               console.log("connectToProtectedSSID successfully!");
>               Alert.alert("connectToProtectedSSID successfully!");
>             },
>             (reason) => {
>               console.log("connectToProtectedSSID failed!");
>               console.log(reason);
>               Alert.alert(reason);
>             }
>           );
>       } else {
>         Alert.alert("Permission denied!");
>       }
>     });

**Comment by coderjoel** [comment]
I'm able to connect to the network on Android 11. Only issue I'm facing is disconnection when the app is in background. Were you able to fix the issue @MattBlanco?

**Comment by GlobusHugoSchmitt** [comment]
The issue, in my case, is that I have another part of the. code monitoring for network changes, and it picks `cellular` as the connection type when connecting to an SSID without internet. It never reports a successful wifi connection. 
(But I'm still trying different things.)

**Comment by mayank2245** [comment]
Hi i am facing issue in my device there is internet available in wifi but when i connect using `connectToProtectedSSID` it shows no internet.
can anyone help

**Comment by samirlegdah** [comment]
@MattBlanco have you managed to find a solution?
