### ISSUE TITLE
Use of undeclared identifier 'UIApplicationOpenSettingsURLString'

### ISSUE THREAD

**Issue by Xiequanxi** [JuanSeBestia/react-native-wifi-reborn#16]
xcode archive Use of undeclared identifier 'UIApplicationOpenSettingsURLString'
![image](https://user-images.githubusercontent.com/22664831/68986440-70c10c00-085a-11ea-8b91-0e3b249f5c83.png)
"react": "16.6.3",
"react-native": "0.58.0",
"react-native-wifi-reborn": "^2.1.1",

**Comment by JuanSeBestia** [comment]
Yep, That happened to me on one of my team's PCs but I couldn't replicate it

**Comment by JuanSeBestia** [comment]
@Xiequanxi, Which version of XCode and iOS you use?
