### ISSUE TITLE
Wifi is getting disconnected when the app is in background

### ISSUE THREAD

**Issue by thisisjoel** [JuanSeBestia/react-native-wifi-reborn#161]
Wifi is getting disconnected when the app is in background. I connect to the wifi inside the app and then when I try to get out of the app the wifi automatically disconnects and connects to my home wifi. Is there a fix for it?

I am using:
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-wifi-reborn": "4.3.7"

**Comment by eliaslecomte** [comment]
Can you also provide Android version and what device models you use?

**Comment by thisisjoel** [comment]
It requires attention

**Comment by vinilprabhu** [comment]
Issue is still present on android 11
