### ISSUE TITLE
WifiManager.setEnabled(true) not working

### ISSUE THREAD

**Issue by melero2000** [JuanSeBestia/react-native-wifi-reborn#165]
Hi, Im trying to use the setEnabled method and it is not working.

I have followed the installation steps correctly, the application has the permissions and other methods work but that one does not.

The methods isEnabled, getCurrentWifiSSID and getIP works perfectly.
![image](https://user-images.githubusercontent.com/45013053/114055767-55143680-9891-11eb-96ff-e9d52031cc12.png)

But when I try to use setEnabled(true) on a button in the onPress method, it does nothing and does not turn on the device's wifi
![image](https://user-images.githubusercontent.com/45013053/114056215-b805cd80-9891-11eb-8c1e-09b1ad0e7f51.png)

Using wifi-reborn 4.3.7 with react native 0.64

_Thanks._

**Comment by eliaslecomte** [comment]
Have you checked source code and underlying Android documentation. This may no longer be possible starting a specific Android version.
