### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by amirmsvi** [JuanSeBestia/react-native-wifi-reborn#166]
Hey, I'm using Expo and VS Code, I keep getting this error upon any function I use:
TypeError: null is not an object (evaluating '_reactNativeWifiReborn.default.setEnabled')
Any help would be extremely appreciated.

**Comment by eliaslecomte** [comment]
I don't think you can use expo with NativeModules? Have a look at previous issues mentioning expo: https://github.com/JuanSeBestia/react-native-wifi-reborn/search?q=expo&type=issues
