### ISSUE TITLE
Network request failed after WiFi reconnection

### ISSUE THREAD

**Issue by spike322** [JuanSeBestia/react-native-wifi-reborn#185]
I'm developing an app for an IoT system where I have an IoT device which needs to be setup through WiFi. This device provides a WiFi access point without Internet connection, so I just connect to this ap using `WifiManager.connectToProtectedSSID()`, I perform a POST request for its configuration and then I perform `WifiManager.disconnect()` for disconnecting to it. Until this point everything works fine, and still when I disconnect from the IoT device my phone automatically reconnects to my WiFi network. The problem is that when it reconnects, my app is no longer able to perform any kind of request on my local network or outside. For instance, I have a local server which works fine, but after WiFi reconnection every request returns `error [TypeError: Network request failed]`. Or I've even got an MQTT broker, and so if I try to reconnect to it it shows `mqtt.event.error connection failure MqttException (0) - java.net.SocketException: socket failed: ENONET (Machine is not on the network)`. The only thing to do is close the app and reopen it. Why it is not able to use the WiFi network anymore?

**Comment by SpiriaJWF** [comment]
@spike322 Hi did you find any solutions for this?

**Comment by rberg-ct** [comment]
I'm having the exact same issue
i can perform fetch commands over wifi connection with internet 
then  I connect to a wifi hotspot on an Iot unit for setup.. WifiManager.connectToProtectedSSID()
post the config  
do a disconnect .. WifiManager.disconnect()
network returns to previous working wifi 
then all fetch commands fail with [TypeError: Network request failed]

has anyone found a solution?? it seems this was incorrectly marked as a stale issue

**Comment by aj-spanio** [comment]
I found how to get this going.... If you do WifiManager.forceWifiUsageWithOptions(true, { noInternet: true }); just after connection succeeds, then a WifiManager.forceWifiUsageWithOptions(false, { noInternet: false }); after disconnection, it will trigger Android to recheck if the new connection is valid, and network requests seem to work again.
It seems the mechanism in play here is that Android marks the IoT device connection as not having internet, but then only re-checks when a connection is explicitly made. Disconnecting from the current wifi network and allowing Android to fall back to the user's previous wifi connection does not trigger this check (though it clearly should).

**Comment by rberg-ct** [comment]
> I found how to get this going.... If you do WifiManager.forceWifiUsageWithOptions(true, { noInternet: true }); just after connection succeeds, then a WifiManager.forceWifiUsageWithOptions(false, { noInternet: false }); after disconnection, it will trigger Android to recheck if the new connection is valid, and network requests seem to work again. It seems the mechanism in play here is that Android marks the IoT device connection as not having internet, but then only re-checks when a connection is explicitly made. Disconnecting from the current wifi network and allowing Android to fall back to the user's previous wifi connection does not trigger this check (though it clearly should).

Hey ... nice work . I had kinda given up hope on this and had to work around this issue 
i can confimn from early signs of testing that this has solved my issue

**Comment by kaleaditya** [comment]
every time i try tu build app (run app) on my phone while the executing process is in progress the wifi  disconnects automatically. please help . and as soon as i close cmd wifi automatically get connected.  what should i do?

**Comment by Andrey2K17** [comment]
try call connectivityManager.bindProcessToNetwork(null) brefore connectivityManager.unregisterNetworkCallback(networkCallback)
