### ISSUE TITLE
How to test it?

### ISSUE THREAD

**Issue by rlesniak** [JuanSeBestia/react-native-wifi-reborn#186]
I want to create some new feature to this lib. How can I test my changes without pushing it to GH? I see `example` folder but inside package.json dependency links to remote, how to run local version of code?

**Comment by rlesniak** [comment]
ha ha ha funny

**Comment by eliaslecomte** [comment]
Hi, for small changes you could just edit in node_modules of your app.
However; the best way to test forks is to commit your changes on your fork and then use your fork as dependency via its github url + git tag. As you would with any npm dependency.
Unfortunately the example doesn't use repo itself. I tried but didn't get it running.
