### ISSUE TITLE
Got Internal Error on IOS

### ISSUE THREAD

**Issue by efazri** [JuanSeBestia/react-native-wifi-reborn#196]
I got internal error when I run in IOS device. I was added `Access Wifi Information` and `Hotspot Configuration` on my project. Anyone can explain to me or give me some advice?

**Comment by SpiriaJWF** [comment]
@efazri  I also have this problem, did you managed to find a solution?

**Comment by efazri** [comment]
@SpiriaJWF the problem was came from my device, I can my device to the other one and it's works
