### ISSUE TITLE
Crash issue in IOS 14 local network permission

### ISSUE THREAD

**Issue by kildip** [JuanSeBestia/react-native-wifi-reborn#198]
Hi @eliaslecomte 

when i get local network permission and crash application . once you  press ok then not crashing application in IOS 14+

Illegal callback invocation from native module. This callback type only permits a single invocation from native code. Can you Please help

**Comment by kildip** [comment]
hello @eliaslecomte ,
 any update ?

**Comment by patrickspafford** [comment]
@kildip Did you find a solution to this?

**Comment by kildip** [comment]
no @patrickspafford

**Comment by lay-mand** [comment]
Same issue here, please help @eliaslecomte , @Rapsssito

**Comment by kildip** [comment]
> @kildip Did you find a solution to this?

are you using any tcp or udp library ?

**Comment by lay-mand** [comment]
> > @kildip Did you find a solution to this?
> 
> are you using any tcp or udp library ?

Maybe it's better to reopen issue?

**Comment by ApWin** [comment]
@kildip I use tcp socket and connectToProtectedSSID still doesn't work. Did you find any solution ?

**Comment by kkch196247** [comment]
-./node_modules/react-native-wifi-reborn/ios/RNWifi.m

```cpp
// #BEFORE:
if ([ssid isEqualToString:[self getWifiSSID]]) resolve(nil);
if ([ssid isEqualToString:[self getWifiSSID]]) {
    resolve(nil);
    return;
}
// #AFTER:
// if ([ssid isEqualToString:[self getWifiSSID]]) resolve(nil);
if ([ssid isEqualToString:[self getWifiSSID]]) {
    resolve(nil);
    return;
}
//
```

**Comment by yedi97** [comment]
i same issue? any update? please help me
