### ISSUE TITLE
IoT Device Disconnects After a Few Seconds in iOS 13

### ISSUE THREAD

**Issue by admah** [JuanSeBestia/react-native-wifi-reborn#2]
In iOS 13, there is a known issue that causes hotspot devices to connect and then disconnect after a few seconds.

- https://forums.developer.apple.com/thread/122540

- https://stackoverflow.com/questions/57894269/ios-13-network-connected-via-nehotspotconfiguration-disconnects-after-a-few-sec

Apparently this can be fixed by setting `configuration.joinOnce = false;` on lines 61 and 84 in `RNWifi.m`.

I'm going to do some independent testing as well, but wanted to create an issue for reference.

**Comment by JuanSeBestia** [comment]
If you solve it, do not hesitate to perform a PR :)

**Comment by admah** [comment]
Adding a comment that updating `configuration.joinOnce = false;` did not seem to resolve the issue.

**Comment by josectobar** [comment]
`configuration.joinOnce = false;` seems to do the trick, just make sure you set it in both wifi connection methods.

**Comment by eliaslecomte** [comment]
@admah  or @josectobar  can you open a PR for this?

**Comment by adnan1naeem** [comment]
this repo is not working in ios 12 plus. if someone has fixed it share link or repo?

**Comment by josectobar** [comment]
@adnan1naeem, what type of error are you getting?

**Comment by adnan1naeem** [comment]
@josectobar   i am facing this  this error "Cant get ssid"

**Comment by eliaslecomte** [comment]
I have created a pr for this. (https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/33)

**Comment by Rapsssito** [comment]
@admah, could test it with `react-native-wifi-reborn` **2.3.1**?
