### ISSUE TITLE
iOS - connectToProtectedSSIDPrefix Throws Error Even when Successful

### ISSUE THREAD

**Issue by patrickspafford** [JuanSeBestia/react-native-wifi-reborn#203]
On version 4.3.8, I can call the connectToProtectedSSIDPrefix on an iOS device with valid params and have that device connect to the expected network, but this method throws an error anyway with

`[Error: Unable to connect to Wi-Fi with prefix /myNetworkName]`

It looks like the connectToProtectedSSIDPrefix method, after trying to establish the connection, is checking that the prefix matches the current network name, which may be the cause here.

```// Verify SSID connection
                if ([ssid isEqualToString:[self getWifiSSID]]){
                    resolve(nil);
                } else {
                    reject([ConnectError code:UnableToConnect], [NSString stringWithFormat:@"%@/%@", @"Unable to connect to Wi-Fi with prefix ", ssid], nil);
                }
```

If the prefix provided is `myNetwork`, that resolves, and the device successfully connects to `myNetworkName`, wouldn't the above check always fail?

**Comment by patrickspafford** [comment]
Replaced the if condition with this:
```
if ([[self getWifiSSID] hasPrefix:ssid]) {
```

And it seems to work. Although when upgrading from 4.3.7 to 4.3.8, I forgot to rerun `pod install` in my project.

What's strange is that even with this modification, SSID prefixes that include a "-" (e.g. "myNetworkPrefix-") will successfully connect and not throw an error, but iOS 14.6 will show an alert saying "Unable to connect to network" anyway.

I think this is an entirely separate issue.

**Comment by IsaacIsrael** [comment]
Hey I don't know if it still validated but I fixed this issue by adding the Access Wi-fi information at the Signin&Capabilities
