### ISSUE TITLE
Error while configuring WiFi after turning off WiFI on physical device

### ISSUE THREAD

**Issue by kidasovmercury** [JuanSeBestia/react-native-wifi-reborn#206]
Today I come across a mysterious error and I still don't know how to figure it out. 

I am using the latest library version 4.3.8
I am trying to connect to a protected WiFI network using this code on my iPad(5th gen, 13.1)

```js
async function connectToWifi(network: string, password: string) {
  await WifiManager.connectToProtectedSSIDPrefix(
    network,
    password,
    false,
  );
}
```

It worked well until I occasionally turned my WiFI off in the settings like this
![Screenshot 2021-08-17 at 17 51 21](https://user-images.githubusercontent.com/50829747/129739280-1bdb27e6-ece3-45d3-ae10-0eeeb079d245.png)

And even after I turned it on, I wasn't able to connect to my WiFI network. This code fails with the error 
```
 {"code":"unableToConnect","message":"Error while configuring WiFi","domain":"NEHotspotConfigurationErrorDomain","userInfo":{"NSLocalizedDescription":"internal error."}
```

Any help will be highly appreciated

**Comment by KevinvdBurg** [comment]
I'm going to continue the chain,

@Adnan48 @ryanstout @kidasovmercury Did you find the fix?

**Comment by pavlo-o-savchuk** [comment]
@KevinvdBurg @Adnan48 @ryanstout @kidasovmercury Did you find the fix?
