### ISSUE TITLE
loadWifiList for iOS

### ISSUE THREAD

**Issue by jkaravakis** [JuanSeBestia/react-native-wifi-reborn#21]
The loadWifiList function is available on Android, Is there a way to implement it for iOS as well?

**Comment by jason102** [comment]
@jkaravakis If you learn how to do this, with this library or another, please share with us here! I'm looking for a solution as well for iOS.

**Comment by jason102** [comment]
Some say with iOS it's not possible, which sounds crazy to me? https://github.com/blackdeve/react-native-wifi/issues/31

**Comment by jkaravakis** [comment]
Based on the below response, it does appear that this is not possible:

https://forums.developer.apple.com/thread/113765

Happy to hear any further suggestions!

**Comment by Rapsssito** [comment]
In iOS is not possible and Android is slowly removing it, too.

**Comment by jkaravakis** [comment]
Interesting, any suggestions on how to manage obtaining an IoT device's WiFi name? In my case, each individual device has a distinct number in the WiFi name.

**Comment by jkaravakis** [comment]
Closing this issue, I discovered that with iOS 13+ you can utilize an initWithSSIDPrefix function. For example, if your device has a "Device_12345" nomenclature you can supply the "Device" portion of the prefix and the function will automatically ask the user to join the network with that prefix. If multiple networks are available with the same prefix, it will ask to join the one with the strongest connection. This avoids needs to search a list of Wifi names for the relevant one.

 I am creating my own branch and building a connectToProtectedSSIDPrefix function. I will open a PR if this is a desirable feature for the community.

**Comment by mi-mazouz** [comment]
Hey I'm facing the same problem. Maybe that library can do the job https://github.com/balthazar/react-native-zeroconf
