### ISSUE TITLE
 On Android 10, the user has to enable wifi manually

### ISSUE THREAD

**Issue by ils-narayanaR** [JuanSeBestia/react-native-wifi-reborn#227]
Getting this error how to solve this ?

**Comment by eliaslecomte** [comment]
This is how Android works. Before Android 10, wifi could be enabled/disabled by apps. Starting Android 10 this is no longer possible.

The best way to handle is, is detect if wifi is on + if the user is on Android10+. If so, show an error and maybe add a (quick) button to open wifi settings, so the user can enable wifi himself.

**Comment by ils-narayanaR** [comment]
Thankq so much for your quick response @eliaslecomte
