### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by cristianoccazinsp** [JuanSeBestia/react-native-wifi-reborn#229]
Hey,

@JuanSeBestia just wondering if you are still maintaining this as I'm looking for a library with similar features.

Thanks,

**Comment by eliaslecomte** [comment]
Hi @cristianoccazinsp.

This library is maintained by a few as you can see in the releases / merge / issues.
I am using it myself to connect through IoT commissioning.
We are welcoming contributions (Android / iOS / React Native) as these features are facing changes with every new release.

**Comment by cristianoccazinsp** [comment]
Great to know. I do collaborate with PRs as I find issues, but I wanted to confirm the library is usable for both iOS and Android as I've seen a few unmaintained ones that required a lot of upfront work.
