### ISSUE TITLE
[iOS] connectToProtectedSSID NEHotspotConfigurationManager completionHandler always returns nil

### ISSUE THREAD

**Issue by jkaravakis** [JuanSeBestia/react-native-wifi-reborn#23]
There appears to be an iOS bug where NEHotspotConfigurationManager errors are only shown to the user and are not sent to the completion handler. This results in the user being shown an "Unable to connect to" error message but the connectToProtectedSSID Promise is always resolved and never rejected. Here is a StackOverflow reference to this issue:

https://stackoverflow.com/questions/57393333/nehotspotconfigurationmanager-unable-to-join

A workaround could be to implement a delay of a few seconds allowing your WiFi network to switch and use getCurrentWifiSSID to confirm the correct WiFi network is connected before proceeding.

**Comment by JuanSeBestia** [comment]
Has a PR #25 in progress with comments

**Comment by jkaravakis** [comment]
I believe PR #25 does not address this issue since it is an entirely separate function.

**Comment by shamilovtim** [comment]
#25 is unrelated

**Comment by Rapsssito** [comment]
@jkaravakis, I created #31. I believe it fixes your issue.
