### ISSUE TITLE
[Android] Does not seem to connect on Android 11

### ISSUE THREAD

**Issue by BernhardtDT** [JuanSeBestia/react-native-wifi-reborn#233]
I am using the `connectToProtectedSSID` call and it asks me if I want to setup a temporary Wi-Fi network to connect to device. This behavior did not happen when I used it on Android 9 it just worked. When I press accept it simply shows my Wi-Fi with an exclamation mark.  

![Screenshot 2022-01-25 at 08 20 03](https://user-images.githubusercontent.com/52275280/150922083-c8dbd355-0a15-42c7-9799-58c0c987e19b.png)

![Screenshot 2022-01-25 at 08 25 15](https://user-images.githubusercontent.com/52275280/150922632-62171cd7-b41b-4dea-bf71-976aaae97ee2.png)

**Comment by dawidchyrzynski** [comment]
@BernhardtDT I'm experiencing the same issue. System shows "Automatically connected via Google" status but there is no connection to the network. How did you manage to solve it?

**Comment by timh1004** [comment]
I'm having the same issue! Any updates? This package is using [`WifiNetworkSpecifier.Builder`](https://developer.android.com/reference/android/net/wifi/WifiNetworkSpecifier.Builder#public-methods_1) that says "_some devices may only support requesting local-only networks_" which seems to be the case here.
The Android Documentation notes, that:

> On Android 11 (SDK level 30) and higher, apps can use the [android.provider.Settings.ACTION_WIFI_ADD_NETWORKS](https://developer.android.com/reference/android/provider/Settings#ACTION_WIFI_ADD_NETWORKS) intent to guide the user through adding one or more new saved networks or Passpoint configurations. The API also works as-is to modify existing saved configurations (https://developer.android.com/guide/topics/connectivity/wifi-save-network-passpoint-config).

That seems to be the proper replacement for the deprecated `WifiManager.addNetwork(WifiConfiguration config)` API.

**Comment by vlad-timotei** [comment]
Hi @timh1004 
Did you find a solution yet?
I will try to update the code to use ACTION_WIFI_ADD_NETWORK, but I'm not super familiar with Java.
Thank you for pointing in the right direction.
