### ISSUE TITLE
Starting Android 9, it's only allowed to scan 4 times per 2 minuts in a foreground app. Handle error before connection

### ISSUE THREAD

**Issue by brookflok** [JuanSeBestia/react-native-wifi-reborn#237]
Hi, I m using react-native-wifi-reborn.
I use it for scanning all available wifi networks, and when the wifi list is loaded a user can press scan again to scan WI-Fi networks again.

According to Android 9 and above a user can scan the wifi network only 4 times, but when a user scans the network more than 4 times he will not get this error he will only get this error if he tries to connect to specific wifi. 

The solution would be to have some error handling that would return to the user that he scanned the network too many times and that he needs to wait for 2 minutes. 

Right now I m counting how many times did the user scan the network but that solution is not covering all the cases so the best way to proceed is to get this error if a user used scanning of the network too many times and that I can handle it when scanning of the network is happening.

**Comment by brookflok** [comment]
Fixed the issue, by doing small changes to the code. 

- Forked this GitHub
- Added changes to RNWifiModule.java

Changes I added are in reScanAndLoadWifiList, I created a boolean that will get the wifi.startScan() and it will return true or false depending on its ability to scan wifi. Then I added an if statement, where I check if the wifiStartScan is true or false. If true I return the list if false I return the promise. rejection with the error and read it in the app.

`    @ReactMethod
    public void reScanAndLoadWifiList(final Promise promise) {
        boolean wifiStartScan = wifi.startScan();
        Log.d(TAG, "wifi start scan: " + wifiStartScan);
        if(wifiStartScan == true){
        final WifiScanResultReceiver wifiScanResultReceiver = new WifiScanResultReceiver(wifi, promise);
        getReactApplicationContext().registerReceiver(wifiScanResultReceiver, new IntentFilter(WifiManager.SCAN_RESULTS_AVAILABLE_ACTION));
        }else{
            Log.d(TAG, "Wifi scan rejected");
            promise.reject("Starting Android 9, it's only allowed to scan 4 times per 2 minuts in a foreground app.");
        }
    }`

**Comment by eliaslecomte** [comment]
Will you pr this?

**Comment by brookflok** [comment]
> Will you pr this?

I have made a PR request you can merge it if you wish.

**Comment by brookflok** [comment]
There is a pull request that should be done and this can be closed
