### ISSUE TITLE
 Start connecting in the application and connect while the app is in the background - Error: On Android 10, the user cancelled connecting (via System UI). 

### ISSUE THREAD

**Issue by brookflok** [JuanSeBestia/react-native-wifi-reborn#238]
Hi, I m experiencing one problem. I wish that my user is able to start connecting in my application and if he put the application in the background while still connecting he should still connect to the network. 
Right now if a user starts the connection and puts the application in the background after a small period of time he will get this error:

> ERROR  Error: On Android 10, the user canceled connecting (via System UI).

I checked the documentation for ThanosFisherman and I saw that they don't have any explanation for this and didn't have that problem. So if someone maybe knows a solution to this problem it would be great.

**Comment by ryanstout** [comment]
@brookflok I'm seeing the same issue, were you able to dup?

**Comment by brookflok** [comment]
@ryanstout Hi Ryan, I'm not able to solve this issue, I will probably write a module for wifi connection or something and try to fix it that way. But it will probably be later because there are bigger priority things to be done. 
If you find some solution for this feel free to share it here.

**Comment by ovy9086** [comment]
I'm seeing this issue without even the user canceling or putting the app in background...

**Comment by goatbarn** [comment]
> I'm seeing this issue without even the user canceling or putting the app in background...

Myself as well. Just upgraded my personal phone/development phone from Samsung S9 to a S21 (which I'm assuming bumped my Android OS version up quite a bit) and now I get this error whilst just attempting to connect to a protected SSID in foreground.

**Comment by ryanstout** [comment]
@goatbarn @ovy9086 Are both of you on Android 10? Thanks

**Comment by ovy9086** [comment]
I'm on Android 12, on a Pixel3a. but by looking at the Android implementation it seems that the native library is throwing this error in the `onUnavailable()` callback, which might trigger for various reason. But the library always rejects with an `USER_CANCELED` error.

**Comment by ryanstout** [comment]
I'm still seeing this issue, any more insights on what causes this issue? Thanks!

**Comment by brookflok** [comment]
Hi with the new update it is working for me without the error. Tested with v4.7.0 

Just a note while I was testing this I noticed that if I don't remove the network before using it, it will try to connect and it will never return an error. It is just connecting to infinity. 

But I found a solution before the connection I remove it with isRemoveWifiNetwork(SSID that I m trying to connect), and then try to connect and it asks me for a temporary connection, and when I press connect it connects 100% of the time. 

So if someone gets the problem that he can connect only when you see the dialog for a temporary connection, then always before connection just remove the network from configuration and it will not make your connection go to infinity.  

If someone finds a better solution than this, it would be good to post.

**Comment by brookflok** [comment]
Okay finally I have found some kind of a solution for this, it is not a pretty one but it is working for me now. So the issue that I had was: 

- I would enter my app and go to the connection screen
- I would initiate scanning of the Wi-Fi 
- While waiting for the Wi-Fi List I would put my app in the background.
- I would wait for 3,4,5 secs and go back to the app
- I would get the On Android 10, the user canceled connecting (via System UI).

So I was looking for a solution, and I found one but it is not something I can recommend for everyone. 

In the **RNWifiModule.java** file, I have modified **ConnectivityManager.NetworkCallback()** 

So basically you can read about the ConnectivityManager here:  https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback

I found that the module is overriding onUnavaible which would return a promise.reject() with this error message. 

I commented that part of the code in the module and I was able to scan for the networks in the background and get their SSID without any rejection or error message. 

 ```
ConnectivityManager.NetworkCallback networkCallback = new
                ConnectivityManager.NetworkCallback() {
                    @Override
                    public void onAvailable(Network network) {
                        super.onAvailable(network);
                        DisconnectCallbackHolder.getInstance().bindProcessToNetwork(network);
                        connectivityManager.setNetworkPreference(ConnectivityManager.DEFAULT_NETWORK_PREFERENCE);
                        if (!pollForValidSSID(3, SSID)) {
                            promise.reject(ConnectErrorCodes.android10ImmediatelyDroppedConnection.toString(), "Firmware bugs on OnePlus prevent it from connecting on some firmware versions.");
                            return;
                        }
                        promise.resolve("connected");
                    }

                    // This is the part I have commented
                    // @Override
                    // public void onUnavailable() {
                    //     super.onUnavailable();
                    //     promise.reject(ConnectErrorCodes.userDenied.toString(), "On Android 10, the user cancelled connecting (via System UI).");
                    // }

                    @Override
                    public void onLost(@NonNull Network network) {
                        super.onLost(network);
                        DisconnectCallbackHolder.getInstance().unbindProcessFromNetwork();
                        DisconnectCallbackHolder.getInstance().disconnect();
                    }
                };
        DisconnectCallbackHolder.getInstance().addNetworkCallback(networkCallback, connectivityManager);
        DisconnectCallbackHolder.getInstance().requestNetwork(nr);
    }
```
