### ISSUE TITLE
[iOS] getWifiSSID returns nil

### ISSUE THREAD

**Issue by jkaravakis** [JuanSeBestia/react-native-wifi-reborn#24]
In iOS, getWifiSSID (triggered within getCurrentWifiSSID after iOS version and location permissions check) is returning nil.

The breakdown appears to be at CNCopyCurrentNetworkInfo which returns a null dictionary despite having location permissions. CNCopySupportedInterfaces is returning (en0).

**Comment by JuanSeBestia** [comment]
What version you have? I have similar issues with iOS 13.1.x

**Comment by jkaravakis** [comment]
I'm using IOS 13.1.3

**Comment by JuanSeBestia** [comment]
Yes, I never understood the reason why.
Only update the OS if you can
