### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[11], "react-native-wifi-reborn").WifiManager.getCurrentWifiSSID')

### ISSUE THREAD

**Issue by RebeccaGibbon** [JuanSeBestia/react-native-wifi-reborn#240]
Hello, when I tried to use this library, I receive the error:
`TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[11], "react-native-wifi-reborn").WifiManager.getCurrentWifiSSID')`

`./gradlew clean` did not solve this, neither did reinstalling my node_modules.

My package.json is included below. 

{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/cli-platform-android": "^6.3.0",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^5.0.1",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-aws-freertos": "^0.1.23",
    "react-native-hce": "^0.1.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.12.0",
    "react-native-vector-icons": "^9.1.0",
    "react-native-wifi-reborn": "^4.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

Thanks for any help!

**Comment by KevinMac19** [comment]
> Hello, when I tried to use this library, I receive the error: `TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[11], "react-native-wifi-reborn").WifiManager.getCurrentWifiSSID')`
> 
> `./gradlew clean` did not solve this, neither did reinstalling my node_modules.
> 
> My package.json is included below.
> 
> { "name": "myapp", "version": "0.0.1", "private": true, "scripts": { "android": "react-native run-android", "ios": "react-native run-ios", "start": "react-native start", "test": "jest", "lint": "eslint ." }, "dependencies": { "@react-native-community/cli-platform-android": "^6.3.0", "@react-navigation/native": "^6.0.6", "@react-navigation/native-stack": "^6.2.5", "lottie-ios": "^3.2.3", "lottie-react-native": "^5.0.1", "react": "17.0.2", "react-native": "0.66.4", "react-native-aws-freertos": "^0.1.23", "react-native-hce": "^0.1.2", "react-native-safe-area-context": "^3.3.2", "react-native-screens": "^3.12.0", "react-native-vector-icons": "^9.1.0", "react-native-wifi-reborn": "^4.5.0" }, "devDependencies": { "@babel/core": "^7.12.9", "@babel/runtime": "^7.12.5", "@react-native-community/eslint-config": "^2.0.0", "babel-jest": "^26.6.3", "eslint": "7.14.0", "jest": "^26.6.3", "metro-react-native-babel-preset": "^0.66.2", "react-test-renderer": "17.0.2" }, "jest": { "preset": "react-native" } }
> 
> Thanks for any help!

Same thing happening with me. Let me know if u found any solution for that.
