### ISSUE TITLE
Android 11 - not working

### ISSUE THREAD

**Issue by billnbell** [JuanSeBestia/react-native-wifi-reborn#241]
What do I need to set for Android 11 ? 

I am having issues using this in Android 11.

**Comment by jackpotdk** [comment]
I am having problems as well after upgrading my device. 

I am running Samsung S10, Android Version 12.

As far as I can tell, WiFi connection fails because of "Android security policy prevents use of WiFi" - At least thats what the phone indicates when the app crashes.

Any thoughts?

**Comment by billnbell** [comment]
OK not idea why this is still occurring but we cannot still connect using this library on Android 11.

Any thoughts?

**Comment by ruialves35** [comment]
Hi, any improvement here? I also can't Turn on/off the wifi using this

**Comment by billnbell** [comment]
We need it fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billnbell** [comment]
Is this package abandoned?
