### ISSUE TITLE
IOS 15 getWifiSSID

### ISSUE THREAD

**Issue by nilaydigiwhiz** [JuanSeBestia/react-native-wifi-reborn#246]
We are having issue getting current wifi SSID on IOS 15.

We are getting error "Cannot detect SSID". We have added location permission but still having same issue

Seems like getWifiSSID returing nil

It works using Xcode but not working when generating IPA and installing on actual device 

Please help

**Comment by alepiumetti** [comment]
I have the same issue and I don't know how resolve it ..

**Comment by nilaydigiwhiz** [comment]
Issue was with location permission. When generated IPA , location permission was not configured properly. After fixing that, issue gone
