### ISSUE TITLE
WifiManager.reScanAndLoadWifiList not working when choosing approximate location

### ISSUE THREAD

**Issue by mi-mazouz** [JuanSeBestia/react-native-wifi-reborn#254]
Hi!

I just discovered an issue on the WifiManager.reScanAndLoadWifiList function. The promise never resolves when the user chooses approximate location.

WifiManager.loadWifiList function returns `Location permission (ACCESS_FINE_LOCATION) is not granted` error.

Both functions are working when precise location is enabled

Anyone else have the same problem?

**Comment by SpiriaJWF** [comment]
From my understanding, to scan nearby Wifi devices you need `ACCESS_FINE_LOCATION`.
https://developer.android.com/guide/topics/connectivity/wifi-permissions

> on previous versions of Android, these apps needed to declare the [ACCESS_FINE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION) permission instead.

**Comment by mi-mazouz** [comment]
@SpiriaJWF ```ACCESS_FINE_LOCATION``` is already in my AndroidManifest.xml file
