### ISSUE TITLE
couldNotDetectSSID :Cannot get current SSID!

### ISSUE THREAD

**Issue by ItxAltaf** [JuanSeBestia/react-native-wifi-reborn#257]
WifiManager.getCurrentWifiSSID().then(
      ssid => {
        console.log("Your current connected wifi SSID is " + ssid);
      },
      () => {
        console.log("Cannot get current SSID!");
      }
    );

Could not get ssid on some android devices?????

**Comment by midhun-sa** [comment]
> 🎉 This issue has been resolved in version 4.7.1 🎉
> 
> The release is available on:
> 
> * [GitHub release](https://github.com/JuanSeBestia/react-native-wifi-reborn/releases/tag/v4.7.1)
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-wifi-reborn/v/4.7.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Hi  @JuanSeBestia I'm Midhun,  Is there any possibility to solve the issue that when connectToProtectedSSID is called the app is connecting to the wifi but it is showing an exclamation mark? there is no internet connection.
