### ISSUE TITLE
WifiManager.reScanAndLoadWifiList() locationServicesOff error does not appear

### ISSUE THREAD

**Issue by voulgarakis** [JuanSeBestia/react-native-wifi-reborn#258]
Hi all,

I use the reScanAndLoadWifiList method in order to forcefully scan WiFi networks. I realized that when Android's phone location service is OFF, the locationServicesOff error does not appear, whereas when using the loadWifiList method with location services OFF the error does appear. 

Anyone else has the same problem?

**Comment by voulgarakis** [comment]
The issue is not with the location permission. The location permission is granted. But even if it is granted is the location service is OFF the reScanAndLoadWifiList method does not return the locationServicesOff error, so when you call reScanAndLoadWifiList with the location service OFF it does not return anything, nor an exception or something and i gets stuck inside the method forever.

**Comment by posymeon** [comment]
I also have this problem
