### ISSUE TITLE
Android packing error reported  Task :react-native-wifi-reborn:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by 1871636671** [JuanSeBestia/react-native-wifi-reborn#259]
An accident occurred while building the app:
![image](https://user-images.githubusercontent.com/66112404/179252365-894ba96a-67a1-489b-862b-d8c0a00a1ffe.png)

My version
![image](https://user-images.githubusercontent.com/66112404/179252659-f286c665-395e-466c-be7f-e6b60e1a9645.png)

Please check it for me

**Comment by 1871636671** [comment]
There were no problems with development and debugging, only with packaging

**Comment by 1871636671** [comment]
There were no problems with development and debugging, only with packaging

**Comment by eliaslecomte** [comment]
It's because the compileSdkVersion, and targetSdkVersion are still set to 29 for react-native-wifi-reborn. You can up those via a patch, or wait until https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/270 is merged.

**Comment by ahammedmishal** [comment]
when doing gradlew assembly release got the error while generating apk file
the compile and target SDK are 33 tried with 30,31,32 also

> Task :react-native-wifi-reborn:verifyReleaseResources FAILED
![Screenshot 2022-11-30 233141](https://user-images.githubusercontent.com/68768299/204873730-ad4b561c-00e9-4e5e-a1fd-8b7a6ff2a763.png)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-wifi-reborn:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed

**Comment by felipesms** [comment]
> and target SDK are 33 tried with 30,31,


Hello. How fix this error?
thanks.
