### ISSUE TITLE
isRemoveWifiNetwork doesnt work on android 12

### ISSUE THREAD

**Issue by sidd2217** [JuanSeBestia/react-native-wifi-reborn#260]
Hi,

isRemoveWifiNetwork() is not working on real device in android 12.
I tried to use disconnect() but that doesnt work either.

Does anyone have a solution for this?

Versions -
React native - 0.66.4
wifi-reborn - 4.7.0
device - Samsung S22+ ( android 12 )

**Comment by SpiriaJWF** [comment]
What do you mean? It returns an error? Is successful but doesn't disconnect?
