### ISSUE TITLE
Android Connects But No Internet

### ISSUE THREAD

**Issue by enchorb** [JuanSeBestia/react-native-wifi-reborn#262]
Hello, 

This library works great for iOS but encountering the same issue as this post https://stackoverflow.com/questions/72457171/react-native-wifi-reborn-connected-to-wifi-but-no-internet-available-with-exc

On Android, the connection is successful but internet does not work.

**Comment by SpiriaJWF** [comment]
Have you tried looking at the `forceWifiUsageWithOptions` option?

**Comment by samirlegdah** [comment]
Unfortunately I also have the same problem, I tried with "forceWifiUsageWithOptions" but nothing changes.

**Comment by enchorb** [comment]
Same, my code looks like this

```
await WifiManager.connectToProtectedSSID(NETWORK_NAME, NETWORK_PASS, false)
      .then(async () => {
        if (Platform.OS === 'android')
          await WifiManager.forceWifiUsageWithOptions(true, { noInternet: true });
      })
      .catch((err) => handleWifiError(err?.code));
  };
```

**Comment by alaincampagno** [comment]
Same, Is there any news for the possibile solution ?

**Comment by ankitpro** [comment]
I'm also facing issue connecting to Wi-Fi.
Can someone please help me?

**Comment by AtakanMavzer** [comment]
Problem persists on version 4.8.3. ``forceWifiUsageWithOptions`` does not work.

**Comment by Sotatek-HuyNguyen12** [comment]
I'm still facing this issue.
Does anyone have a solution?
