### ISSUE TITLE
On Android 10, the user cancelled connecting (via System UI)

### ISSUE THREAD

**Issue by Jack-QMY** [JuanSeBestia/react-native-wifi-reborn#265]
![image](https://user-images.githubusercontent.com/57746139/185530329-99bbe0e9-cc14-418c-a36a-28bb61fe6ad2.png)
in android. Why do I enter the correct password and the connection is successful, but the password is entered incorrectly and the following picture problem occurs

**Comment by Jack-QMY** [comment]
Inside the WifiManager.connectToProtectedSSID method

**Comment by SpiriaJWF** [comment]
The error message is changed in this PR #264
