### ISSUE TITLE
Android 13, http requests not being sent.

### ISSUE THREAD

**Issue by vchan023** [JuanSeBestia/react-native-wifi-reborn#276]
Hi, 
Have used this library for a while for IoT wifi setups but recently started running into an issue on Android 13.

After calling `connectToProtectedSSID`, I send a request to the device's access point to retrieve nearby wifi signals.
When called, `connectToProtectedSSID` is returning  'connected'. However the request is not being received by the device. Looking through ADB logs I don't see any information about the request or the SSID we connect to.

Does this library fully support Android 13 yet? Is there any permissions on this library end that need to be added?

Testing on:
 -Android 13
 -Google Pixel 7 
 -React native 70.3

**Comment by daaanigm** [comment]
I'm having the same problem. Did you found something?? @vchan023

**Comment by timothyPatterson** [comment]
Ensure clear text traffic is allowed. In Android manifest:
```
<application
           android:usesCleartextTraffic="true"> 
```
Also checkout forceWifiUsageWithOptions method to force Android to use WiFi (as opposed to routing traffic through mobile data).
```
    if(Platform.OS === 'android'){
      await WifiManager.forceWifiUsageWithOptions(true, {noInternet: true});
    }
```

**Comment by daaanigm** [comment]
Thanks @timothyPatterson, but it is not working with your suggestions.

Android manifest contains usesCleartextTraffic="true" and even using forceWifiUsageWithOptions(true, {noInternet: true}) the problem persists.

The problem is that it connects to the network but the router is inaccessible.

In case it helps, this problem does not happen on a device running Android 10, but it does happen on a device running Android 12.

I also tried to test the library with a clean app, with Android SDK 31 because I thought it could be the problem but not, the problem persist.

Any other suggestion?
Thanks in advance!

**Comment by daaanigm** [comment]
> Hi, Have used this library for a while for IoT wifi setups but recently started running into an issue on Android 13.
> 
> After calling `connectToProtectedSSID`, I send a request to the device's access point to retrieve nearby wifi signals. When called, `connectToProtectedSSID` is returning 'connected'. However the request is not being received by the device. Looking through ADB logs I don't see any information about the request or the SSID we connect to.
> 
> Does this library fully support Android 13 yet? Is there any permissions on this library end that need to be added?
> 
> Testing on: -Android 13 -Google Pixel 7 -React native 70.3

Did you found any solution for that? I'm still having this issue.
Thanks in advance!

**Comment by vchan023** [comment]
> > Hi, Have used this library for a while for IoT wifi setups but recently started running into an issue on Android 13.
> > After calling `connectToProtectedSSID`, I send a request to the device's access point to retrieve nearby wifi signals. When called, `connectToProtectedSSID` is returning 'connected'. However the request is not being received by the device. Looking through ADB logs I don't see any information about the request or the SSID we connect to.
> > Does this library fully support Android 13 yet? Is there any permissions on this library end that need to be added?
> > Testing on: -Android 13 -Google Pixel 7 -React native 70.3
> 
> Did you found any solution for that? I'm still having this issue. Thanks in advance!

I ended up purchasing another Google pixel to test android 13 on another device and didn't have any issues. For now everything seems to be working fine for us.

**Comment by daaanigm** [comment]
> i got this thing working by adding the new NEARBY_WIFI_DEVICES permission https://developer.android.com/reference/android/Manifest.permission#NEARBY_WIFI_DEVICES in androidmainfest.

Yes, It is necessary for Android 13 (SDK 33), but I'm having the problem with Android 11 (SDK 32 AND 31) and Android 12 (SDK 30), the app said "connected" but is like as no real connection, if you go to wifi settings you can see "Connected by AppName" but I have no internet connection. I can ping the device from my app, but not from a browser.

If I try to do a ping with a terminal I received the message "connect: Network is unreachable". Seems to be only accessed by the app who created the connection. (Not a real wifi connection)

Any help?
Thanks in advance!
