### ISSUE TITLE
Update SDK Version Android

### ISSUE THREAD

**Issue by AlbinCederblad** [JuanSeBestia/react-native-wifi-reborn#283]
I have to go to node_modules of react-native-wifi-reborn and update 

compileSdkVersion 31
buildToolsVersion '31.0.0'
targetSdkVersion 31

otherwise release build fails.

**Comment by hakansaglam29** [comment]
I faced also the same problem, then I changed compile, buildTools and target SDK versions to 31 in android/build.gradle and made a new patch. Now i am able take a release build. Thanks @AlbinCederblad
