### ISSUE TITLE
How to install on Android RN 6.0+

### ISSUE THREAD

**Issue by tshiamor-adft** [JuanSeBestia/react-native-wifi-reborn#29]
Hi could I get better clearity on how to install on versions on RN 6.0 and above. Im new to rn.
1) I understand the library supports autolinking, I did a normal install via yarn add, however functions still fail at runtime, as they are  undefined.
 
2) Do we still need to use "import com.reactlibrary.RNWifiPackage;"  in RN 6.0. also is if so it in MainActivity.java or MainApplication.java. documentation says MainActivity.java not sure if there's a typo or intentional.

3) adding "import com.reactlibrary.RNWifiPackage;" MainApplication causes a compilation error, with a complaint that the package doesn't not exist.

**Comment by JuanSeBestia** [comment]
You had ran this steps:
```
yarn add react-native-wifi-reborn
cd ios && pod install
```

**Comment by tshiamor-adft** [comment]
thanks @JuanSeBestia , but I believe those are steps for ios. The confusion is concerning react native on android, for RN0.60+, as it only supports auto link.

**Comment by eliaslecomte** [comment]
So with autolinking the library is linked in the android project automatically. npm i react-native-wifi-reborn and you are ready to use it. Are you having issues?
