### ISSUE TITLE
Can't disconnect from WiFi in IOS

### ISSUE THREAD

**Issue by bankiprudhvi** [JuanSeBestia/react-native-wifi-reborn#290]
this method not working in iOS devices. please help on this 

await WifiManager.disconnectFromSSID(ssid)
              .then(
              () => console.warn('success disconnect'),
              e => {
              console.warn('failure disconnect', e);
              },
              )
              .catch(e => {
              console.log('error', e);
              });

**Comment by varda-altusnova** [comment]
@bankiprudhvi have u managed to resolve or find an issue with that?

**Comment by varda-altusnova** [comment]
> [varda-altusnova] Lower version supported but i need latest version support for further

which version works for you?

**Comment by kozhinas** [comment]
> joinOnce: true

it doesn't work for me

**Comment by kozhinas** [comment]
> > joinOnce: true
> 
> it work for me

stopped working
