### ISSUE TITLE
Prevent iOS from asking user to authenticate to get internet connection

### ISSUE THREAD

**Issue by jackpotdk** [JuanSeBestia/react-native-wifi-reborn#291]
I am using react-native-wifi-reborn on iOS to pair with an iOT device. 

The iOT device provides an IP over DHCP when connected to the hotspot. However, the iOS device aparently determines that there is no Internet access, so it automatically opens a browser in the attempt to get the user to authenticate for Internet access.

It there a way to prevent this behavior?

**Comment by varda-altusnova** [comment]
@jackpotdk have u managed to solve that?

**Comment by jackpotdk** [comment]
@varda-altusnova Not yet, no :(

**Comment by varda-altusnova** [comment]
@jackpotdk what about android 10+ version? does it work for you with and iot device?

**Comment by jackpotdk** [comment]
@varda-altusnova Yeah, I am on Android 12 (Galaxy S10) which works fine. Happy to share source if you need?

**Comment by varda-altusnova** [comment]
@jackpotdk would be appreciated to see the result. Can't decide if this lib will meet project needs.

**Comment by jackpotdk** [comment]
@varda-altusnova Shoot me an email on jackpotdk@gmail.com
