### ISSUE TITLE
none of the methods work on ios 16

### ISSUE THREAD

**Issue by kozhinas** [JuanSeBestia/react-native-wifi-reborn#296]
Hello everyone, not one of the methods specified in the documentation for iOS 16 does not work for me, I can’t connect and disconnect from Wi-Fi, if I provide geolocation and access to networks, but this does not help, what could be the problem? Or is it a library issue?

**Comment by kozhinas** [comment]
maybe there are some other libraries that can solve this problem? I didn't find it, it's all outdated

**Comment by DemoWearing** [comment]
Hi, it's working for me on iOS 16, perhaps you didn't add the `Privacy - Location When In Use Usage Description` description to your info.plist?

**Comment by kozhinas** [comment]
hi, Apple did not allow external testing without this information, it's strange that it works for you, I heard that the library developer is aware of this problem

**Comment by kozhinas** [comment]
i always get the error 'internal error.', 'unableToConnect'

**Comment by kozhinas** [comment]
У меня все полу

> Hi, it's working for me on iOS 16, perhaps you didn't add the `Privacy - Location When In Use Usage Description` description to your info.plist?

Thank you, you helped me, I realized that I didn’t add it in xcode hotspot configuration
