### ISSUE TITLE
Cannot detect SSID

### ISSUE THREAD

**Issue by ncofrem** [JuanSeBestia/react-native-wifi-reborn#3]
In iOS 13 with "example/AwesomeProject" always get:

**"Cannot get current SSID! Cannot detect SSID"**

I granted location permissions.

- iPhome model: iPhone 7 
- iOS Version: 13.1.3

Thanks you!

**Comment by JuanSeBestia** [comment]
You already tried to put this capability in your project and in your distribution profile.

<img width="1004" alt="Screen Shot 2019-10-28 at 4 20 05 PM" src="https://user-images.githubusercontent.com/7362688/67719251-7801a200-f99f-11e9-9f44-b4c590b18793.png">


I create the sample project to test library implementation things, but I didn't test the example very carefully. I will try it

**Comment by JuanSeBestia** [comment]
Sorry man, in iOS I could not make the example worked, if it is not putting a project that has a correct profile and obviously I can not share it :(

**Comment by Valiums** [comment]
hey @ncofrem I had exactly the same issue. Everything was well setup and it worked on ios 12 however no luck on ios 13 then I realized that we were both using the same ios version (13.1.3).. So I just updated to 13.2.3 and it fixed the problem for me! Hope that help you too if you haven't already figured out yet!

and thanks @JuanSeBestia for this package :)

**Comment by Hashir524** [comment]
I cannot get SSID on 13.2.3, it was working fine on the previous versions. 11, 12. What can be the issue?

**Comment by JuanSeBestia** [comment]
now toy need Location permission for iOS13+ https://github.com/JuanSeBestia/react-native-wifi-reborn#ios-13

**Comment by digitlninja** [comment]
WHat does "Correct profile" mean for Ios-13??? 
Im getting the error despite following the ios setup docs. @JuanSeBestia
