### ISSUE TITLE
addOrUpdateFailed

### ISSUE THREAD

**Issue by JulesCourtois** [JuanSeBestia/react-native-wifi-reborn#30]
Hi,

I'm getting the following error message :
`Error: Could not add or update network configuration with SSID <SSID>`
When trying to use `connectToProtectedSSID` on android with an IoT Amazon Button.

The capabilities of the network are `[WPA2-PSK-CCMP+TKIP][WPA-PSK-TKIP+CCMP][ESS]`

This is my code
`await WifiManager.reScanAndLoadWifiList(
                  wifiList => {
                    let wifiArray = JSON.parse(wifiList);
                    let ssids = wifiArray.map(value => value.SSID);
                    let buttonWifi = ssids.find(value =>
                      value.startsWith('Button ConfigureMe'),
                    );
                    console.warn('buttonWifi: ' + JSON.stringify(wifiArray));
                    WifiManager.connectToProtectedSSID(
                      buttonWifi,
                      '8367H28S',
                      false, // isWep
                    ).then(
                      success =>
                        console.warn(
                          'Connected successfully! ' + JSON.stringify(success),
                        ),
                      error =>
                        console.warn('Connection failed! ' + error.toString()),
                    );
                  },
                  error =>
                    console.warn(
                      'Error getting wi-fi list: ' + error.toString(),
                    ),
                );`

I've also tried connecting to other wi-fi networks with the same error.
I've made sure that `PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION` is `GRANTED`

Any tips on what could be going wrong ?

**Comment by JulesCourtois** [comment]
I've found the solution.

This was caused by Android behaviour which only allows an app to modify a network state if it was added by said app and not by another app or the user.

> Wi-Fi and Networking Changes
> This release introduces the following behavior changes to the Wi-Fi and networking APIs.
> Your apps can now change the state of WifiConfiguration objects only if you created these objects. You are not permitted to modify or delete WifiConfiguration objects created by the user or by other apps.
> Previously, if an app forced the device to connect to a specific Wi-Fi network by using enableNetwork() with the disableAllOthers=true setting, the device disconnected from other networks such as cellular data. In This release, the device no longer disconnects from such other networks. If your app’s targetSdkVersion is “20” or lower, it is pinned to the selected Wi-Fi network. If your app’s targetSdkVersion is “21” or higher, use the multinetwork APIs (such as openConnection(), bindSocket(), and the new bindProcessToNetwork() method) to ensure that its network traffic is sent on the selected network.

[Source](https://developer.android.com/about/versions/marshmallow/android-6.0-changes)

**Comment by ammarkhan967** [comment]
@JulesCourtois 
we are facing the same problem with android 10. can you please the solution???

**Comment by JulesCourtois** [comment]
@ammarkhan967 
Try forgetting the network before connecting again.

**Comment by adnan1naeem** [comment]
> @ammarkhan967
> Try forgetting the network before connecting again.

@JulesCourtois  The solution is not working .Can you please sugggest any method that could work as its's alternate or some other solution which could work in android 10

**Comment by eliaslecomte** [comment]
Actually if you are using the latest version you also have to target Android 10. I've updated the sample (to also target android 10) here: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/105
