### ISSUE TITLE
WiFi List for iOS

### ISSUE THREAD

**Issue by Tejas-Sharma2627** [JuanSeBestia/react-native-wifi-reborn#300]
I want to get the list of all the available networks in the proximity of the device. For Android, it is loadWifiList(). Is their any method to load the Wifi List in iOS?

**Comment by kozhinas** [comment]
> I want to get the list of all the available networks in the proximity of the device. For Android, it is loadWifiList(). Is their any method to load the Wifi List in iOS?

you can't

**Comment by luhaimin** [comment]
I also encountered the same problem, iOS cannot use the loadWifiList() method

**Comment by meenakshi-ss** [comment]
issue still exists, please provide a solution for this

**Comment by alexrififi** [comment]
> issue still exists, please provide a solution for this

no solution for this 🫤
