### ISSUE TITLE
Android 12-13 disconnect

### ISSUE THREAD

**Issue by kozhinas** [JuanSeBestia/react-native-wifi-reborn#304]
no methods to disable wifi work, there is
ideas how to implement it?

**Comment by aboozaid** [comment]
You can try [react-native-tethering](https://react-native-tethering.onrender.com/) which has this feature.

**Comment by kozhinas** [comment]
> You can try [react-native-tethering](https://react-native-tethering.onrender.com/) which has this feature.

I tried it, it didn't help, too much legacy code will have to be changed for it

**Comment by Desintegrator** [comment]
same
