### ISSUE TITLE
WifiManager.loadWifiList() not working in IOS

### ISSUE THREAD

**Issue by suganyaanbusaravanan** [JuanSeBestia/react-native-wifi-reborn#310]
When i am trying to list the available wifi list from iOS getting error like"TypeError: _reactNativeWifiReborn.default.loadWifiList is not a function. (In '_reactNativeWifiReborn.default.loadWifiList()', '_reactNativeWifiReborn.default.loadWifiList' is undefined)"

**Comment by kozhinas** [comment]
it can't be done in ios
