### ISSUE TITLE
WIFI - disconnect or isRemoveWifiNetwork not working - Android

### ISSUE THREAD

**Issue by iOSMahesh** [JuanSeBestia/react-native-wifi-reborn#311]
I've installed the latest version 4.8.3

Project version info
React native: 0.67.4
React: 17.0.2
Node: 16.0.0
Platform: Android

I could able to scan, connect the wifi but I can't able to disconnect/remove WIFI. 

I tested with 
OnePlus Nord - Android 12,
MI A2 - Android 10, 
Samsang tablet - Latest

`        const result = await WifiManager.isRemoveWifiNetwork(currentSSID)
`
Also, tried .disconnect()

Return success but when we checked status at system setting WIFI status is connected.

**Comment by Desintegrator** [comment]
same issue
