### ISSUE TITLE
Question: Does It need to apply Apple Network Extension?

### ISSUE THREAD

**Issue by yosimasu** [JuanSeBestia/react-native-wifi-reborn#32]
@JuanSeBestia 

Thanks for nice library.

When integrate this library into projects. Does it need to apply [Apple Network Extension](https://developer.apple.com/documentation/networkextension)?

**Comment by Rapsssito** [comment]
@yosimasu, since it uses `NEHotspotConfigurationManager` and modifies the WiFi configuration, I think it does.

**Comment by yosimasu** [comment]
@Rapsssito 

Does it need a special entitlement?
Something like an entitlement for Hotspot Helper API.
Or just enable network extension capability.

**Comment by Rapsssito** [comment]
@yosimasu, I only enabled network extension capability and works fine.
