### ISSUE TITLE
`WifiManager.getCurrentWifiSSID()` never fulfilled

### ISSUE THREAD

**Issue by WeeJeWel** [JuanSeBestia/react-native-wifi-reborn#321]
When calling `WifiManager.getCurrentWifiSSID()`, the returned Promise never resolves or rejects.

Maybe related: when calling `WifiManager.connectToSSIDPrefix('Foo-')`, an error `Error while configuring WiFi` is thrown.

I'm using Expo in Development mode.

```bash
$ npx expo config --type introspect
...
        entitlements: {
          'aps-environment': 'development',
          'com.apple.developer.networking.HotspotConfiguration': true,
          'com.apple.developer.networking.wifi-info': true
```

```json
    "expo": "~49.0.8",
    "react": "18.2.0",
    "react-native": "0.72.4"
```

**Comment by vipulav-j** [comment]
I am also facing same issue. I am getting this error.  undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[5], "react-native-wifi-reborn").WifiManager.getHotspotState')
My project dependencies are as follow.

```
"react": "17.0.2",
    "react-native": "0.68.3",
    "react-native-wifi-reborn": "^4.8.3"

**Comment by gerarts** [comment]
You need to make sure you have location permissions granted.

The reason for this is that you can use a WiFi network's name to reverse search someone's location. (There are databases online to do this).

It's weird that there isn't an error in place for when you haven't done this. But mostly a DX problem.

If you are using expo, check out [`expo-location`](https://docs.expo.dev/versions/latest/sdk/location/) for docs on installing and checking for permissions. (Don't forget to add the plugin to your `app.json`) 😉

**Comment by WeeJeWel** [comment]
I'm not sure. Shouldn't this Promise reject with an error that the permission is missing?
