### ISSUE TITLE
Why is it necessary to specify a Node version?

### ISSUE THREAD

**Issue by MagnasiePro** [JuanSeBestia/react-native-wifi-reborn#322]
I'm always facing this error during a yarn add:
The engine "node" is incompatible with this module. Expected version "16.18.0". Got "20.6.1"

It is working normally with yarn --ignore-engines, so why do we need to limit this library to Node 16.18.0?

**Comment by JuanSeBestia** [comment]
Hmm I don't think that the js lib that we use has node dependency. I think we can remove or support more than 16

**Comment by GaWr26** [comment]
This also gives me a big issue as I'm using Expo Application Services for building and build fails. Unfortunately there's nothing I can do on the Expo Environment side to get past this issue. Could you please remove the dependency?

**Comment by bearkillerPT** [comment]
No idea why this is still an issue but if you do encounter this issue see [this](https://docs.expo.dev/eas/json/#eas-build) (just CTRL+F "node").
You can force node and yarn versions on the EAS build! 
Just use the value that your dependency says it expects and it will install if fine.

**Comment by skarm61** [comment]
@bearkillerPT it doesn't install as with 

### eas.json file body:
``` 
{
    "build": {
        "base": {
            "node": "19.3.0"
        },
     ...
}
```
as without this section in the config at all.
Always has the same error
```
error react-native-wifi-reborn@4.10.0: The engine "node" is incompatible with this module. Expected version "16.18.0". Got "19.3.0"
```

**Comment by GaWr26** [comment]
Thanks! That's exactly what I was looking for and wasn't aware it's possible

**Comment by pritamparker** [comment]
any solution so far ?
