### ISSUE TITLE
Android 13 local Websocket

### ISSUE THREAD

**Issue by GaWr26** [JuanSeBestia/react-native-wifi-reborn#323]
Our app connects to our IoT device's local mqtt broker via Websocket over WiFi and the brokers IP address. We use `forceWifiUsageWithOptions` for this as there might be no internet on the device. This worked perfectly untill upgrading our app to Android 13 SDK Version 33. Now the local connection only works in a expo dev build, not in the release. There's no requests arriving at the broker.

Anybody aware of breaking changes that prevent a LAN connection via Websocket? Are we missing any permissions?

We're really lost at the moment and any help is highly appreciated 👍

**Comment by JuanSeBestia** [comment]
Do you know if this MR solve the problem? 

https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/319

**Comment by notjulian** [comment]
> Our app connects to our IoT device's local mqtt broker via Websocket over WiFi and the brokers IP address. We use `forceWifiUsageWithOptions` for this as there might be no internet on the device. This worked perfectly untill upgrading our app to Android 13 SDK Version 33. Now the local connection only works in a expo dev build, not in the release. There's no requests arriving at the broker.
> 
> Anybody aware of breaking changes that prevent a LAN connection via Websocket? Are we missing any permissions?
> 
> We're really lost at the moment and any help is highly appreciated 👍

do you have ` react_native_config.xml` with `domain-config cleartextTrafficPermitted="true"`

**Comment by GaWr26** [comment]
I added `domain-config cleartextTrafficPermitted="true"` and now it works again. Thank you very much for pointing this out!
