### ISSUE TITLE
IOS 17. Cannot read property 'connectToProtectedSSID' of null

### ISSUE THREAD

**Issue by mouadFahsi** [JuanSeBestia/react-native-wifi-reborn#325]
When trying to use the plugin on iOS I keep getting this error `Cannot read property 'connectToProtectedSSID' of null`
![image](https://github.com/JuanSeBestia/react-native-wifi-reborn/assets/20311674/23e07fa7-2bf9-41ae-9a8f-f2b1744cafbf)
`"dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-wifi-reborn": "^4.8.3"
  },`

**Comment by tora-golia** [comment]
IOS17.  Got the same issue

**Comment by jawknees** [comment]
having the same issue on ios. Android is working fine

**Comment by Wolfleader101** [comment]
Hey, did anyone find an fix for this?
