### ISSUE TITLE
isRemoveWifiNetwork does not work

### ISSUE THREAD

**Issue by despossivel** [JuanSeBestia/react-native-wifi-reborn#34]
I'm trying to forget about a network, I pass to the ISRemoveWifiNetwork its SSID, and the callback returns me true, but the network is not forgotten. Has anyone ever experienced this?

I am granting WRITE_SETTINGS permission

**Comment by Rapsssito** [comment]
@despossivel, could you provide more info about your system? (OS, react-native-wifi-reborn version, RN version, etc.).

**Comment by eliaslecomte** [comment]
This only works when your app connected with the wifi network in the first place. Is that the case?

**Comment by despossivel** [comment]
@Rapsssito O SO é ANDROID 8, RN is the last.

@eliaslecomte  And yes it is connected

**Comment by eliaslecomte** [comment]
I meant, if the app made the connection (by using connectWithProtectedSSID), it should also be able to remove it. If you made the connection yourself (in wifi settings), the app will not be able to remove it.

**Comment by despossivel** [comment]
huuuuum, I didn't get to observe that. but I will check
