### ISSUE TITLE
starting IOS 17 connectToSSID opens a webportal/captive Portal

### ISSUE THREAD

**Issue by ateker01** [JuanSeBestia/react-native-wifi-reborn#342]
Hello all,

I have an IOT device that creates an access point. It does have SSID shown but it does not require a password.

Before IOS 17, my react native app would connect to this SSID by using connectToSSID method with no problems. 

After IOS 17, when the same connectToSSID method is called, the phone exits out of my app, opens the phone's WiFi settings and then automatically opens a captive portal. 

Can anyone think of any way to stop the IOS device open this captive portal / webportal?

Thanks in advance

**Comment by silaspedrosa** [comment]
After all my research, I couldn't find anything you can do on the app side. You should disable the portal in the device's code.

There are some things to consider, though. If your app sends an http request to the device containing the wifi credentials, I noticed that if you take too long to send this request, the Captive Portal has a better chance of appearing. If you send them as soon as possible, then the device could connect to the new wifi fast enough so it stops being an acess point and iOS might not even show the Captive Portal.

**Comment by ateker01** [comment]
Thank you very much for checking.

Since IOS 17 always launches the captive portal, can you think of a way to force launch the Captive Portal on IOS 16?

I don't mind the captive portal as long as it shows the same behaviour among the different IOS versions (16 or 17).

**Comment by dbaonguis-wfc** [comment]
> Thank you very much for checking.
> 
> Since IOS 17 always launches the captive portal, can you think of a way to force launch the Captive Portal on IOS 16?
> 
> I don't mind the captive portal as long as it shows the same behaviour among the different IOS versions (16 or 17).

I am also interested to show the captive portal page when the wifi is guarded by it

**Comment by dbaonguis-wfc** [comment]
> Hello all,
> 
> I have an IOT device that creates an access point. It does have SSID shown but it does not require a password.
> 
> Before IOS 17, my react native app would connect to this SSID by using connectToSSID method with no problems.
> 
> After IOS 17, when the same connectToSSID method is called, the phone exits out of my app, opens the phone's WiFi settings and then automatically opens a captive portal.
> 
> Can anyone think of any way to stop the IOS device open this captive portal / webportal?
> 
> Thanks in advance

Hi, which version of `react-native-wifi-reborn` and what method/function did you call to invoke the captive portal?
