### ISSUE TITLE
android build issue from recent package update

### ISSUE THREAD

**Issue by deeds-29** [JuanSeBestia/react-native-wifi-reborn#343]
after a recent package update;  this library version 4.3.7 is not building on Android throwing an error

"/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:107: error: package undefined does not exist
[2023-10-27T21:40:21.661Z] import undefined.RNWifiPackage "

can anyone mention who to fix this issue?

**Comment by silaspedrosa** [comment]
I'm sorry if this feels like a silly question 😅 , but did you try cleaning up gradle and node_modules? 

If you're unsure on how to do that, just clone your project in another folder and start from there.

**Comment by deeds-29** [comment]
@silaspedrosa don't be too silly 😅 even 6 months of experience would do that and I too tried 😁, it didn't work, and in the last commit changes made in the "AndroidManifest.xml" file of the path "android/src/main" of this library caused the issue, when I add 'package="com.reactlibrary.rnwifi"' in the same file it worked fine.

**Comment by evan1715** [comment]
reference potential relationship with [#345](https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/345#issuecomment-1791636498) comment

**Comment by luan-nvg** [comment]
/Users/luanscerqueira/Projects/redgtech-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:71: error: package undefined does not exist
import undefined.RNWifiPackage;
                ^
/Users/luanscerqueira/Projects/redgtech-app/android/app/src/main/java/com/redgtech/MainApplication.java:22: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
/Users/luanscerqueira/Projects/redgtech-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:145: error: cannot find symbol
      new RNWifiPackage()
          ^
  symbol:   class RNWifiPackage
  location: class PackageList

**Comment by sagarhudge-eaton** [comment]
@deeds-29  do you have any updates on this, as I am facing a similar issue?

I have fixed a similar kind of issue related to npm by `downgrading` the npm version but no luck with this npm

**Comment by deeds-29** [comment]
I got it fixed by using "react-native-wifi-reborn": "4.7.0" version, or you can add 'package="com.reactlibrary.rnwifi"'  to "AndroidManifest.xml" file of the path "android/src/main" of this library,  try this one https://www.npmjs.com/package/react-native-wifi-reborn-iinvsys

**Comment by sagarhudge-eaton** [comment]
@deeds-29 Thank you, it is the way I am using this from the past, but it fails when I run the build pipeline. need the proper solution

**Comment by deeds-29** [comment]
please try the above link

**Comment by bihellzin** [comment]
This is still happening.

**Comment by deeds-29** [comment]
Yes.

**Comment by jayadelson** [comment]
Still happening.
