### ISSUE TITLE
How to enable Access WIFI Information, with correct profile from EXPO

### ISSUE THREAD

**Issue by ferMartz** [JuanSeBestia/react-native-wifi-reborn#35]
Hi,

First of all, thanks for making this code available.

I'm running a react native app directly from expo(V0.61). 
I'm not running any emulator, is it possible to add the profile as specified in the instructions directly in expo or in react native? Sorry I'm a bit confused there.

Thanks in advance!!!

FM

**Comment by JuanSeBestia** [comment]
Sorry for the delay, I'm not sure about how to configure the capabilities of iOS on Expo

I think you will need to eject the project to do that

**Comment by ferMartz** [comment]
@JuanSeBestia 

No worries, I created a new react native without expo and I'm planning to add react-native-wifi-reborn. I will let you know how it goes :-)

**Comment by ferMartz** [comment]
@JuanSeBestia 

I'm closing this since I created a NEW react native native without expo.
However, when you have a chance can you take a look at this [issue #64](https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/64)

Thanks!
