### ISSUE TITLE
connectionStatus() is returning 'false' when the Wi-Fi is connected.

### ISSUE THREAD

**Issue by sanzsans** [JuanSeBestia/react-native-wifi-reborn#350]
I got that function:

try {
            await WifiManager.connectToProtectedSSID(
                username,
                password,
                false,
                false,
            );
            Toast.show({type: 'success',text1: 'Successfull '+ username});
        } catch (error) {
            Toast.show({type: 'error',text1: 'Error.'});
        }

My device connects to the network. But if I go into settings it appears: "Connected to the network XX available through [App_name] This makes that when I use the ConnectionStatus() function it appears that it is NOT connected (I can make API requests from the App but I can NOT access the internet from the browser).

**Comment by jawknees** [comment]
this is what's happening to mine on android also. The app connects to the wifi successfully but it appears to not have any internet connection. I think it's just saying it connected successfully to the wifi and that's just it
