### ISSUE TITLE
Failed to build the app: No package name found. 

### ISSUE THREAD

**Issue by sagarhudge-eaton** [JuanSeBestia/react-native-wifi-reborn#351]
After the npm install and pod install I received the following issue 

`Failed to build the app: No package name found. Found errors in /Users/MyApp/node_modules/react-native-wifi-reborn/android/src/main/AndroidManifest.xml.

[!] Invalid `Podfile` file: 859: unexpected token at 'info Run CLI with --verbose flag for more details.`

**Comment by CreeperLin** [comment]
modifying the first line in AndroidManifest.xml as this solves the issue

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.reactlibrary.rnwifi">`
