### ISSUE TITLE
Build error when upgrading to version 4.10.1 (latest). Previously 4.7.0

### ISSUE THREAD

**Issue by Asharuddin-90** [JuanSeBestia/react-native-wifi-reborn#358]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/viraj/Desktop/Qqueridoo/qeridoo-app/node_modules/react-native-wifi-reborn/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':react-native-wifi-reborn'.
> Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-wifi-reborn'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s

Can someone help me ?

**Comment by DavideViolante** [comment]
Maybe you need react-native 0.73 or higher in the package json.

**Comment by Asharuddin-90** [comment]
Thanks for the suggestion

**Comment by bhadresh12** [comment]
> FAILURE: Build completed with 2 failures.
> 
> ## 1: Task failed with an exception.
> * Where:
>   Build file '/home/viraj/Desktop/Qqueridoo/qeridoo-app/node_modules/react-native-wifi-reborn/android/build.gradle' line: 19
> * What went wrong:
>   A problem occurred evaluating project ':react-native-wifi-reborn'.
> 
> > Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>   ==============================================================================
> 
> ## 2: Task failed with an exception.
> * What went wrong:
>   A problem occurred configuring project ':react-native-wifi-reborn'.
> 
> > compileSdkVersion is not specified. Please add it to build.gradle
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>   ==============================================================================
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/6.9.4/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 5s
> 
> Can someone help me ?

If you still get the issue then try this

You can add `package="com.reactlibrary.rnwifi"` to "AndroidManifest.xml" 
or replace
`<manifest xmlns:android="http://schemas.android.com/apk/res/android">`
to
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
     package="com.reactlibrary.rnwifi">`
     
 And comment 
` namespace = "com.reactlibrary.rnwifi"` line in build.gradle.

**Comment by lukiinhas1616** [comment]
@Asharuddin-90 @bhadresh12 
Did it work for you?

**Comment by lukiinhas1616** [comment]
Same problem here, tried both solutions, but don't work.
