### ISSUE TITLE
CONTRIBUTION: Update EXAMPLE project

### ISSUE THREAD

**Issue by alexma01** [JuanSeBestia/react-native-wifi-reborn#360]
HI,

can I update the example project? It's too old and the "RNWifiReborn" example project doesn't work well.
I would like to help if I can!
@gustavoabel 

Thank you

**Comment by gustavoabel** [comment]
Hello, yes I can. what do you think? @JuanSeBestia

**Comment by JuanSeBestia** [comment]
Obviously, feel free to create an MR

**Comment by alexma01** [comment]
Hi,

i created this [PR](https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/368)
