### ISSUE TITLE
Cannot connect to protected SSID on IOS when there's no internet

### ISSUE THREAD

**Issue by Audrey-Ann** [JuanSeBestia/react-native-wifi-reborn#364]
When I the IPhone (IOS) device tries to connect to **a protected WIFI without internet connection** using

```
connectToProtectedSSID(ssid, password, false, false)
```

An error is thrown: `NEHotspotConfigurationErrorDomain: internal error.` at line `154` in `RNWiFI.m`

<img width="1139" alt="Screenshot 2024-02-20 at 3 15 04 PM" src="https://github.com/JuanSeBestia/react-native-wifi-reborn/assets/16864703/574f8897-0294-4c42-aad3-27185e8538be">

Dependencies:
```
"react-native": "^0.73.4",
"react-native-wifi-reborn": "^4.11.0",
```

**Comment by alexma01** [comment]
Hi @Audrey-Ann ,

have you followed all the configuration necessary for the correct use of the library on IOS?
