### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by kalraneeraj24550** [JuanSeBestia/react-native-wifi-reborn#37]
```javascript
import WifiManager from "react-native-wifi-reborn";
    WifiManager.connectToProtectedSSID(wifiNameText, wifiPasswordText, false)
            .then(() => {
                alert('success')
                console.log('Connected successfully!')
            }, () => {
                alert('failure')
                console.log('Connection failed!')
            })
```
### Expectation
It should connect to wifi when i enter correct ssid, password

### Reality
When i enter correct ssid and wrong password it says ''Connected successfully!'' and in wifi list it shows the ssid that i were trying to connect with   

OS: Android

Now i rebuild the application , and i try to connect it says failure all the time even if i enter correct credentials

**Comment by Rapsssito** [comment]
@kalraneeraj24550, thanks for the feedback! Could you provide more info about your set-up (RN version, react-native-wifi-reborn version...)?
