### ISSUE TITLE
v4.12.x produces a runtime error when `connectToProtectedSSID` is called on iOS

### ISSUE THREAD

**Issue by dylankenneally** [JuanSeBestia/react-native-wifi-reborn#379]
I've found that by upgrading the version of `react-native-wifi-reborn` I'm using from version `4.11.0` to `4.12.0` (or `4.12.1`), my app produces the runtime error shown in the screenshot below on my iOS devices. (I have not had the chance to check on Android, but am happy to if it would help investigations).

![image](https://github.com/JuanSeBestia/react-native-wifi-reborn/assets/12589363/2f990513-629b-4b90-b347-f91ac2319a92)

Text content of the image below:

`Argument 4 (NSNumber) of WifiManager.connectToProtectedSSIDis marked as nullable but React requires that all NSNumber arguments are explicitly marked as nonnull' to ensure compatibility with Android.`

More than happy to try contribute/assist, so please do let me know if you need more information, or if there is anything I can do to assist in resolving the issue.

**Comment by stelioskat** [comment]
I can confirm the same issue on iOS too. Android works..

**Comment by mahouza** [comment]
Can confirm this issue still exists.

**Comment by joshh01** [comment]
I'm not quite sure what the proper solution is here, but this is what worked for me.

The docs say: 
`### NEW VERSION WITH OPTIONAL PARAMETERS ###

connectToProtectedWifiSSID({
      ssid: string;
      password: string | null;
      isWEP?: boolean;
      isHidden?: boolean;
      timeout?: number
  ;}): Promise`

However it doesn't appear that isWep, isHidden or timeout are optional for iOS. I fixed it by using:
`WifiManager.connectToProtectedSSID('ssid', 'pass', false, false, 0)`

This is weird though, I have another app where I only used 4 arguments and it works without complaining. Seems it just takes some playing around to get it working.

**Comment by dylankenneally** [comment]
Issue is still present, commenting to reset the actions/stale timer.

**Comment by DavideViolante** [comment]
Another issue opened with same problem I think https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/396

**Comment by aj-spanio** [comment]
Running into this issue as well. Relating to the above comment of `I have another app where I only used 4 arguments and it works without complaining`, I think the issue here is the react native version. Works without issue in react native 0.70.14, but we get this error (with a hard crash, not just a warning) once upgrading to 0.72.0.

This occurs on both iOS and Android.

Anyone have ideas on how to patch this? Needed to upgrade to RN 72 for other reasons, so I am scrambling for a solution to release the app update.
