### ISSUE TITLE
"connectToProtectedSSIDPrefix" isnt available

### ISSUE THREAD

**Issue by tsVestor** [JuanSeBestia/react-native-wifi-reborn#38]
The documented function connectToProtectedSSIDPrefix() is not implemented in Android.

```
WifiManager.connectToProtectedSSIDPrefix("test", null, false).then(
      () => {
        console.log("Connected successfully!");
      },
      () => {
        console.log("Connection failed!");
      }
    )
```

This function is also not included in `react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java`

**Comment by Rapsssito** [comment]
This is a bug in the documentation. It has been updated on 932eb9b82f3d994135caf795c1e2b62a7dbc0d7e!
