### ISSUE TITLE
Could not determine the dependencies of task ':react-native-wifi-reborn:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by daguanren21** [JuanSeBestia/react-native-wifi-reborn#380]
version: 4.12.1
environment: Gradle 8.0  java17

warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info JS server already running.
info Installing the app...

> Configure project :react-native-video
useExoplayerIMA:false
5 actionable tasks: 5 up-to-date
                                                                                                                                  
info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-wifi-reborn:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Cannot query the value of this provider because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by bhadresh12** [comment]
I have found the solution and It was working fine for me in "react-native-wifi-reborn": "4.12.1".

You can add `package="com.reactlibrary.rnwifi"` to "AndroidManifest.xml" 
or replace
`<manifest xmlns:android="http://schemas.android.com/apk/res/android">`
to
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
     package="com.reactlibrary.rnwifi">`
