### ISSUE TITLE
Cannot detect SSID, failed in iOS 

### ISSUE THREAD

**Issue by vipulav-j** [JuanSeBestia/react-native-wifi-reborn#385]
I want to get current SSID name to check that my iPhone is connected with which Wi-Fi. I installed this lib and put the below code for location permission in my info.plist file.
      

```
        <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Always and in usage permissions for Location</string>
	<key>NSLocationWhenInUseUsageDescription</key>
  	<string>Location when in use</string>
```

  	
  	I have iOS 17.4.1 in my iPhone, so i put below code into info.plist file as per this link.
  	https://stackoverflow.com/questions/64676100/how-to-get-ssid-of-currently-connected-wifi-network-in-swift-ios-14
  	

`  	<key>com.apple.developer.networking.wifi-info</key> <true/>`

  	
  	App also ask me to ON location from settings but after that getting below error
  	Error: Cannot detect SSID
  	
  	Another way I used to put code in iOS file and make bridge. below is my code for bridge but that also didn't work.
  	
```

  	RCT_REMAP_METHOD(currentSSID,
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
  
        NSString *kSSID = (NSString*) kCNNetworkInfoKeySSID;
        RCTLogInfo(@"kSSID %@", kSSID);
        NSArray *ifs = (__bridge_transfer id)CNCopySupportedInterfaces();
        for (NSString *ifnam in ifs) {
          NSDictionary *info = (__bridge_transfer id)CNCopyCurrentNetworkInfo((__bridge CFStringRef)ifnam);
          RCTLogInfo(@"kSSID info %@", info);
          RCTLogInfo(@"currentSSID %@", info[kSSID]);
          if (info[kSSID]) {
            
            resolve(info[kSSID]);
            return;
          }
        }
      
      reject(@"cannot_detect_ssid", @"Cannot detect SSID", nil);
    }

```

getting error like below
kSSID SSID
kSSID info (null)
currentSSID (null)

can you please help to solve this issue?
thanks

**Comment by vipulav-j** [comment]
I am still facing the issue. If anyone have resolved it, please share here. Is there any changes in developer account? Should I have to generate new provisioning profile with wifi entitlements and Network extensions?

**Comment by eliottparis** [comment]
@vipulav-j It seems that giving location permission is not enough to get the SSID, it also requires having the "Precise location" on/authorized.

![image](https://github.com/user-attachments/assets/c9ba64b4-331d-4771-8141-c6ac0047ead3)
