### ISSUE TITLE
loadWifi for iOS

### ISSUE THREAD

**Issue by marionboynton1** [JuanSeBestia/react-native-wifi-reborn#39]
will a loadwifi function to show available networks for ios be created? And can one connect to one of the networks by selecting the network on the list on the app?

**Comment by Rapsssito** [comment]
@marionboynton1, sadly, iOS does not allow to retrieve all the available networks. However, you should take a look at **[connectToProtectedSSIDPrefix()](https://github.com/JuanSeBestia/react-native-wifi-reborn#connecttoprotectedssidprefixssidprefix-string-password-string-iswep-boolean-promise)**, it might help you!
