### ISSUE TITLE
Prepare react-native-wifi-reborn for React Native New Architecture (Fabric)

### ISSUE THREAD

**Issue by gustavoabel** [JuanSeBestia/react-native-wifi-reborn#395]
I would like to know if we have or will have any movement to migrate the library to the new react native architecture, I would be very grateful if you gave me feedback @JuanSeBestia.

**Comment by JuanSeBestiaStoerk** [comment]
Do we have any cons? or just pros?

**Comment by gustavoabel** [comment]
@JuanSeBestiaStoerk I don't know if I understand, could you be clearer please?

**Comment by JuanSeBestia** [comment]
I haven't looked at how to build a plugin in frabic yet or if it can be migrated from there.

I was wondering if you've looked at the pros and cons of doing so if you have any in mind. They may require quite a bit of work and I'm not sure how much I'm interested in that. Or if the community also want to.
