### ISSUE TITLE
Add Sponsor button

### ISSUE THREAD

**Issue by Rapsssito** [JuanSeBestia/react-native-wifi-reborn#42]
@JuanSeBestia, could we enable the `Sponsor` button on this repo? There might be some users interested in supporting our work!

**Comment by JuanSeBestia** [comment]
I'm not sure about that

**Comment by Rapsssito** [comment]
@JuanSeBestia, an sponsor button will increase the visibility of funding options for the library. You can read more about it [here](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository).
It will allow us to display a link for our Patreon, GitHub Sponsors, etc. It may be a controversial decision. **This is a suggestion. I leave to your judgment.**
