### ISSUE TITLE
connectToProtectedSSID should update network configuration if password changed. 

### ISSUE THREAD

**Issue by ljbatwh** [JuanSeBestia/react-native-wifi-reborn#47]
When there is a configured wrong Wifi hotspot in the Android wifi setting, the connectToProtectedSSID failure.
Reproduce steps:
1. on the Android WiFi setting page, join a WiFi, such as 'WiFi 1', with a wrong password. No doubt, it will fail.
2. then call connectToProtectedSSID with the correct password

Expected:
connectToProtectedSSID return sucess

Actually:
connectToProtectedSSID timeout

By looking at the code, found the code does not check if the existed network configuration is the same as passed in network SSID and password. here should have some code to update the network if the password has changed.

**Comment by eliaslecomte** [comment]
You can actually remove it first yourself by calling isRemoveWifiNetwork(ssid) but there is one problem with this you can't fix; if the wifi network configuration was created by the user or by another app, your own app can't remove it.

**Comment by ljbatwh** [comment]
@eliaslecomte Thanks for your solution. Yes, in my situation, I can not guarantee to remove the Wifi because maybe the user created the WIFI configuration. But in this situation, call wifiManager.updateNetwork() also will fail, right? In this situation, should we reject the promise by throw an exception to indicate the existed Wifi configuration is not the same as we passed in?

**Comment by eliaslecomte** [comment]
If this PR: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/46 is accepted and a new version is published, this condition will actually be checked. (try to remove or if that fails, try to connect with saved connection). Also the promise will actually be rejected if it couldn't connect in this case.

**Comment by Rapsssito** [comment]
@ljbatwh, thanks for the feedback! **I am closing this issue since #46 was merged**.

If the problem persists, feel free to reopen this issue.

**Comment by rachitgupta98** [comment]
hey @Rapsssito @eliaslecomte 
connectToProtectedSSID does not work if password changes, is there any way to connect with the network other than going to wifi setting, forget the network and then connect.

**Comment by eliaslecomte** [comment]
Yes unfortunately this is how Android is. I am curious, since, starting Android 10, the network configuratin isn't persisted in Wifi Settings, if this is also still a problem.
