### ISSUE TITLE
Error after npm install

### ISSUE THREAD

**Issue by giambafiume** [JuanSeBestia/react-native-wifi-reborn#50]
FAILURE: Build failed with an exception.

What went wrong:
```
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library
[:react-native-wifi-reborn] 
path\node_modules\react-native-wifi-reborn\android\build\intermediates\library_manifest\debug\AndroidManifest.xml 
as the library might be using APIs not available in 16        
Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.reactlibrary.rnwifi" to force usage (may lead to runtime failures)
```

**Comment by giambafiume** [comment]
I've tried to change the minSdkVersion both in gradle and AndroidManifest.
This is the new error:



Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
241 actionable tasks: 30 executed, 211 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> Could not read path 'path \android\app\build\intermediates\transforms\mergeJniLibs\debug\0'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Rapsssito** [comment]
Run `cd android && ./gradlew clean` before building so your build intermediates can reset.

**Comment by Rananjaya** [comment]
minSdkVersion cannot be smaller than version declared in library -minSdkVersion cannot be smaller than version declared in library
