### ISSUE TITLE
Functions aren't responding properly on Android

### ISSUE THREAD

**Issue by Sascha1997** [JuanSeBestia/react-native-wifi-reborn#51]
This is maybe a bad question :|

I have successfully implemented react-native-wifi-reborn into my app, but none of the functions are responding properly on Android.

For example getCurrentWifiSSID is giving the following logged response "Your current connected wifi SSID is <unknown ssid>"

connectToProtectedSSID is catching a failure, and loadWifiList is succeeding but returning an empty array.

I am using React Native 0.61.3, and did not link. Do I need to manually request WiFi permissions from the user?

Thank you!

**Comment by eliaslecomte** [comment]
You need to request location permission first ;-). As you can read on the 'readme'; https://github.com/JuanSeBestia/react-native-wifi-reborn. Here you can see how to: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/45/files
