### ISSUE TITLE
WifiAware

### ISSUE THREAD

**Issue by theIYD** [JuanSeBestia/react-native-wifi-reborn#57]
Is [this](https://developer.android.com/guide/topics/connectivity/wifi-aware) supported in React Native ?

**Comment by eliaslecomte** [comment]
Not yet in this library. Not sure about others. Should ask this on Stackoverflow...

**Comment by theIYD** [comment]
@eliaslecomte Okay, if i may ask, how can we implement it from scratch in React Native ?
