### ISSUE TITLE
Enable Hotspot Configuration in iOS

### ISSUE THREAD

**Issue by nashvent** [JuanSeBestia/react-native-wifi-reborn#61]
In the readme the instructions for iOS this requirement (Hotspot Configuration) is missing

**Comment by eliaslecomte** [comment]
I'm not an iOS expert, but does that hotspot config not gets added when selecting the Access WIFI Information?

**Comment by nashvent** [comment]
I was thinking the same thing. But in Xcode 11.3.1 I see that it's separated
![capture](https://user-images.githubusercontent.com/18234702/78875041-e8aeef00-7a12-11ea-9127-f507509d46bd.jpg)

**Comment by Hugogsalas** [comment]
yes, I think is necessary add this instruction into the README file, I was two hours trying and searching
