### ISSUE TITLE
error: package androidx.core.content does not exist

### ISSUE THREAD

**Issue by gwheele1** [JuanSeBestia/react-native-wifi-reborn#62]
Task :react-native-wifi-reborn:compileDebugJavaWithJavac
C:\Project\node_modules\react-native-wifi-reborn\android\src\main\java\com\react
library\utils\PermissionUtils.java:10: 
error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;

Any ideas for solving this?

**Comment by eliaslecomte** [comment]
On what react native version are you? I assume you will have to update if you want to use the latest version of react-native-wifi-reborn.
