### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNativeWifiReborn.default.getBSSID')

### ISSUE THREAD

**Issue by turanmehmetb** [JuanSeBestia/react-native-wifi-reborn#63]
Hi, whenever i try a function from this lib it gets me this error:
`TypeError: null is not an object (evaluating '_reactNativeWifiReborn.default.getBSSID')`

I ve read #52 but couldnt relate at all. Im using android and didnt use expo. Here is my package.json:

 {
  "name": "hihts",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "start cmd.exe /c react-native start && cd src && cd server && start cmd.exe /c node cassandraServer.js && node mysqlServer.js",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/picker": "^1.1.2",
    "@rodrigogs/mysql-events": "^0.6.0",
    "@xmpp/client": "^0.9.2",
    "@xmpp/time": "^0.11.0",
    "assert": "^2.0.0",
    "axios": "^0.19.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "cassandra-driver": "^4.5.1",
    "child_process": "^1.0.2",
    "connect-timeout": "^1.9.0",
    "crypto": "^1.0.1",
    "dns": "^0.2.2",
    "eslint-config-rallycoding": "^3.2.0",
    "express": "^4.17.1",
    "firebase": "^7.2.2",
    "gyp": "^0.5.0",
    "https": "^1.0.0",
    "https-browserify": "0.0.1",
    "kerberos": "^1.1.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "mysql": "^2.17.1",
    "native-base": "^2.13.8",
    "navigationbar-react-native": "0.0.5",
    "net": "^1.0.2",
    "nodemon": "^2.0.2",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-autogrow-input": "^0.2.1",
    "react-native-dimension": "^1.0.6",
    "react-native-elements": "^1.2.7",
    "react-native-htmlview": "^0.15.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-level-fs": "^2.0.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-randombytes": "^2.0.0",
    "react-native-render-html": "^4.1.2",
    "react-native-router-flux": "^3.45.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-smart-picker": "^1.0.5",
    "react-native-svg": "^9.13.6",
    "react-native-vector-icons": "^6.6.0",
    "react-native-wifi-reborn": "^3.1.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "socket.io": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "stream": "0.0.2",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "7.6.4",
    "@babel/plugin-transform-runtime": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.6.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.51.1",
    "path": "^0.12.7",
    "react-test-renderer": "16.9.0",
    "rn-nodeify": "^6.0.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "react-native": {
    "crypto": "react-native-crypto",
    "https": "https-browserify",
    "fs": "react-native-level-fs"
  },
  "browser": {
    "crypto": "react-native-crypto",
    "https": "https-browserify",
    "fs": "react-native-level-fs"
  }
}

**Comment by eliaslecomte** [comment]
Your dependencies look quite OK. Have you tried resetting packager / node_modules?
How does your import look like?

**Comment by turanmehmetb** [comment]
yes i have tried.  My import code:

` import WifiManager from 'react-native-wifi-reborn';`

**Comment by Rapsssito** [comment]
@turanmehmetb, could you try two things?
* First try with `cd android` and run `./gradlew clean`.
* If it doesn't work try to reinstall your `node_modules`.

**Comment by Rapsssito** [comment]
@turanmehmetb, `getBSSID` is only available on Android, are you using Android in your tests?

**Comment by turanmehmetb** [comment]
yes im using android

**Comment by Rapsssito** [comment]
@turanmehmetb, could you try two things?
* First try with `cd android` and run `./gradlew clean`.
* If it doesn't work try to reinstall your `node_modules`.
