### ISSUE TITLE
Cannot get current SSID on iOS simulator

### ISSUE THREAD

**Issue by ferMartz** [JuanSeBestia/react-native-wifi-reborn#64]
I followed the instructions for iOS and I can't make it work on the simulator. 

First, I spent several hours on a 'real' project to no avail.
Now I was trying do it with the simplest react app that I just created to test this library but no luck.

Here is what I see on the console:
[Mon Apr 20 2020 11:51:22.160]  LOG      Running "wifi" with {"rootTag":1,"initialProps":{}}
[Mon Apr 20 2020 11:51:22.161]  LOG      Connection failed!
[Mon Apr 20 2020 11:51:22.161]  LOG      Cannot get current SSID!

Here is my json:

`
{
  "name": "wifi",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-wifi-reborn": "^3.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.4.0",
    "eslint": "^6.8.0",
    "jest": "^25.4.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

Here is my App.js

`import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';
import WifiManager from 'react-native-wifi-reborn';
import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const App = () => {
  WifiManager.connectToProtectedSSID('wifiName', 'dshfhjdsfga' , false).then(
    () => {
      console.log("Connected successfully!");
    },
    () => {
      console.log("Connection failed!");
    }
  );
  WifiManager.getCurrentWifiSSID().then(
    ssid => {
      console.log("Your current connected wifi SSID is " + ssid);
    },
    () => {
      console.log("Cannot get current SSID!");
    }
  )
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <Header />
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
          <View style={styles.body}>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Step One</Text>
              <Text style={styles.sectionDescription}>
                Edit <Text style={styles.highlight}>App.js</Text> to change this
                screen and then come back to see your edits.
              </Text>
            </View>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>See Your Changes</Text>
              <Text style={styles.sectionDescription}>
                <ReloadInstructions />
              </Text>
            </View>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Debug</Text>
              <Text style={styles.sectionDescription}>
                <DebugInstructions />
              </Text>
            </View>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Learn More</Text>
              <Text style={styles.sectionDescription}>
                Read the docs to discover what to do next:
              </Text>
            </View>
            <LearnMoreLinks />
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});

export default App;`

I appreciate any help!

Thanks

**Comment by notjulian** [comment]
@ferMartz 
same problem here ... the same code works on a physical device but not in a simulator

https://stackoverflow.com/questions/25113027/ios-detect-connected-network-name-in-simulator-and-device

**Comment by Rapsssito** [comment]
Discussion moved to #71
