### ISSUE TITLE
Explain Origin of your source code

### ISSUE THREAD

**Issue by anctsys** [JuanSeBestia/react-native-wifi-reborn#65]
Hello
I wish to have information on your source code of origins.

The source code you used to make react-native-wifi-reborn comes from https://github.com/robwalkerco/react-native-wifi
And this one itself comes from https://github.com/blackdeve/react-native-wifi/.
Can you explain to me why you did not use the code of @blackdeve to initialize the development of your application?

Bruno

**Comment by Rapsssito** [comment]
@JuanSeBestia
