### ISSUE TITLE
Remove allowBackup=true

### ISSUE THREAD

**Issue by scarlac** [JuanSeBestia/react-native-wifi-reborn#67]
Unable to build on Android due to an error caused by allowBackup set to false in my app but in the library it's set to true. The conflict means app devs have to override the setting for all tools which seems unnecessary.
The setting can be removed from the library.

Please see this dicussion on the topic which describes what I just said:
https://github.com/OfficeDev/msa-auth-for-android/issues/21

**Comment by eliaslecomte** [comment]
This is already reported; https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/54

**Comment by scarlac** [comment]
Dupelicate
