### ISSUE TITLE
connectToProtectedSSID does not behave as expected on Android

### ISSUE THREAD

**Issue by dimgrav** [JuanSeBestia/react-native-wifi-reborn#68]
package.json dependency versions:
```
"react": "16.8.6",
"react-native": "0.60.3",
"react-native-wifi-reborn": "^3.1.2"
```
Tested on **Xiaomi A2 Lite** running **Android Q**:

When running `connectToProtectedSSID()` on Android, my app seems to be connecting to the network, the Android notification pane status for Wifi changes to `"Connected via using app-name-here"`, but it does not seem to have internet connectivity.

If I "forget" the network and connect to it from within the OS, my internet connectivity works as expected.

**Comment by eliaslecomte** [comment]
Is it a network without or with internet?

**Comment by dimgrav** [comment]
It has internet connectivity that works properly.

**Comment by eliaslecomte** [comment]
I am investigating this.

**Comment by eliaslecomte** [comment]
I've opened this PR: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/74.
