### ISSUE TITLE
Should connectToProtectedSSIDPrefix work in the iPhone Simulator?

### ISSUE THREAD

**Issue by Pczek** [JuanSeBestia/react-native-wifi-reborn#71]
I've been trying to get `connectToProtectedSSIDPrefix` to work. 
The JS error states 
`Error while configuring WiFi`
Whereas  the XCode console states 
`NEHotspotConfigurationHelper failed to communicate to helper server.`

The answer in the apple dev forums says I need to have certain entitlements enabled.
https://forums.developer.apple.com/thread/127834

I double-checked and surely have all the mentioned entitlements enabled. Even enabled the `NetworkExtension` entitlement  (https://developer.apple.com/documentation/networkextension).
Which was also talked about in this issue => https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/32

Nevertheless, it does not work in the simulator and shows the same error. On the phone, however, it works, even without the `NetworkExtension` entitlements and only the ones mentioned in the apple dev forum.

So my assumption is that at least `connectToProtectedSSIDPrefix` is not usable in the simulator? Quite a pain if so, as it's also unpleasant to work with the phone especially if it's connecting to another wifi without the metro bundler running 🙃

**Comment by notjulian** [comment]
Hi,
you need to use a physical device ...
to debug use ngrok (ngrok http 8081) and change the default development server
and add these entitlements:
![Screenshot 2020-05-21 at 13 07 21](https://user-images.githubusercontent.com/2241601/82553565-93fba980-9b64-11ea-93ec-be79347759cd.png)

**Comment by Rapsssito** [comment]
> So my assumption is that at least connectToProtectedSSIDPrefix is not usable in the simulator? Quite a pain if so, as it's also unpleasant to work with the phone especially if it's connecting to another wifi without the metro bundler running

Yes, `connectToProtectedSSIDPrefix` it is not usable on the simulator. Plus, the constant WiFi metro connection for React Native development does not make things easier.
If someone knows a hacky way, more than welcome!

**Comment by notjulian** [comment]
> > So my assumption is that at least connectToProtectedSSIDPrefix is not usable in the simulator? Quite a pain if so, as it's also unpleasant to work with the phone especially if it's connecting to another wifi without the metro bundler running
> 
> Yes, `connectToProtectedSSIDPrefix` it is not usable on the simulator. Plus, the constant WiFi metro connection for React Native development does not make things easier.
> If someone knows a hacky way, more than welcome!

hi @Rapsssito ,
I've used this method
change bundler to a internet bundler using a ngrok tunnel

1. ngrok http 8081
![Screenshot 2020-05-27 at 16 06 10](https://user-images.githubusercontent.com/2241601/83031447-d9244d80-a034-11ea-8132-266e1cd25a55.png)

2. Configure bundler
![Screenshot 2020-05-27 at 16 07 22](https://user-images.githubusercontent.com/2241601/83031347-bbef7f00-a034-11ea-9f6c-262b5dd06354.png)

3. Paste http address and change port to 80
![Screenshot 2020-05-27 at 16 05 47](https://user-images.githubusercontent.com/2241601/83031705-2ef8f580-a035-11ea-8456-ebbe4146612c.png)
