### ISSUE TITLE
forceWifiUsage causes all network requests to fail

### ISSUE THREAD

**Issue by jcarioti** [JuanSeBestia/react-native-wifi-reborn#76]
I'm trying to connect to an IoT-like device that has a hotspot but does not have internet. If I don't call forceWifiUsage(true), then I can get successful responses using fetch and RNFetchBlob. If I try to force wifi usage, however, all of my proceeding requests fail. When using fetch, I see `TypeError: Network request failed` and when using RNFetchBlob I'm seeing `Error: socket failed: ENONET (Machine is not on the network)`.

I'm having a hell of a time trying to understand what's happening. Any help would be greatly appreciated.

**Comment by eliaslecomte** [comment]
I assume with 'then I can get successful responses using fetch and RNFetchBlob' that you mean against a public url and not with your IoT-like device?

**Comment by jcarioti** [comment]
> I assume with 'then I can get successful responses using fetch and RNFetchBlob' that you mean against a public url and not with your IoT-like device? What are your proceeding requests? To the same IoT-device or to an url on the internet?
> 
> By forceWifiUsage all of the requests your app triggers, are going to the IoT access point.
> So if you want to call something on the IoT access point, and then do a regular api call to the internet you have to:
> 
> 1. forceWifiUsage(true)
> 2. do api call against IoT AP
> 3. forceWifiUsage(false)
> 4. do other api calls   (also, maybe disconnect from AP?)

All requests are going to the IoT AP. I need to connect to the AP, make some API calls, and then disconnect without the OS disconnecting me automatically.

As of right now, I can't get requests to succeed if I force wifi usage before connecting to the AP. 

Also, I cannot disconnect from the AP using the `isRemoveWifiNetwork` function.

**Comment by eliaslecomte** [comment]
You first need to connect to the AP, then you can forceWifiUsage.

isRemoveWifiNetwork on < Android 10 only works if the wifi network was not yet in the saved networks list.

**Comment by jcarioti** [comment]
> You first need to connect to the AP, then you can forceWifiUsage.

That seems to be working. Thank you!

> isRemoveWifiNetwork on < Android 10 only works if the wifi network was not yet in the saved networks list. It can't remove a network that the user or another app created first.

I'm on Android 10 and it won't disconnect immediately. When it does disconnect, it won't reconnect to the known, nearby home network afterwards. The phone just sits without a wifi connection until I force close the app. Once the app is closed, the phone will connect to the known home wifi again. 

Is this the proper order to disconnect?:
```
await WifiManager.forceWifiUsage(false);
console.log('Disconnect from', this.state.ssid);
const disconnectSuccess = await WifiManager.isRemoveWifiNetwork(this.state.ssid);
console.log('Success', disconnectSuccess);
```

**Comment by eliaslecomte** [comment]
Yes the code looks correct to me. Did you test on multiple devices?

**Comment by uranashel44** [comment]
@eliaslecomte , my issue got the same with this issue.

**Comment by jcarioti** [comment]
> Yes the code looks correct to me. Did you test on multiple devices?

I tested on a Pixel 3a. It didn't work, so I didn't move on to any other devices. I wrote my own using NativeBridge and it's working perfectly.

**Comment by coffteam2020** [comment]
@jcarioti , can you please share your code?

**Comment by jcarioti** [comment]
Connecting and locking to a network:
```
        val hotspotSpecifier = WifiNetworkSpecifier.Builder()
                .setSsid(hotspotSSID);

        val hotspotConnectRequest = NetworkRequest.Builder()
                .addTransportType(NetworkCapabilities.TRANSPORT_WIFI)
                .removeCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
                .setNetworkSpecifier(hotspotSpecifier.build())
                .build();

        connectivityCallback = object : ConnectivityManager.NetworkCallback() {
            override fun onAvailable(network: Network) {
                super.onAvailable(network);

                if (lock) {
                    // Lock the device to this network and force all network requests
                    connectivityManager.bindProcessToNetwork(network);
                    wifiLock = wifiManager.createWifiLock(WifiManager.WIFI_MODE_FULL_HIGH_PERF, "WIFI_LOCK");
                }

                promise.resolve("SSID_CONNECTION_SUCCESS");
            }

            override fun onUnavailable() {
                super.onUnavailable();
                promise.reject("SSID_CONNECTION_FAILED", "Could not connect to $hotspotSSID");
            }

            override fun onLost(network: Network) {
                super.onLost(network)

                System.out.println("Lost network...")
                System.out.println(network.toString())
            }
        }

        connectivityManager.requestNetwork(hotspotConnectRequest, connectivityCallback);
```

Releasing a lock and disconnecting:
```
        try {
            connectivityManager.unregisterNetworkCallback(connectivityCallback)

            // Calling removeNetworkSuggestions with an empty list will remove
            // all network connections that have been suggested by this app.
            //
            // This should force a disconnect from the locked network and will
            // let the device go back to a known network.

            val networkSuggestions = listOf<WifiNetworkSuggestion>()
            wifiManager.removeNetworkSuggestions(networkSuggestions)

            if (::wifiLock.isInitialized && wifiLock.isHeld) {
                wifiLock.release();
            }

            connectivityManager.bindProcessToNetwork(null)

        } catch(e: Throwable){
            // Wifi Lock may have already been released at this point
        }
```
