### ISSUE TITLE
Lint Error in Android from using wifi.getConfiguredNetworks

### ISSUE THREAD

**Issue by cashc** [JuanSeBestia/react-native-wifi-reborn#77]
Running an android build after installing this module causes the build to fail because of this linter error:
```
* What went wrong:
Execution failed for task ':react-native-wifi-reborn:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /Users/cashc/repos/my-project/node_modules/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java:283: Error: Missing permissions required by WifiManager.getConfiguredNetworks: android.permission.ACCESS_FINE_LOCATION [MissingPermission]
          final List<WifiConfiguration> mWifiConfigList = wifi.getConfiguredNetworks();
```

I believe the fix is to ask for permission to use location services before calling the `getConfiguredNetworks` function, as outlined in this SO answer https://stackoverflow.com/a/33731050. I'm happy to take a stab at implementing this if the maintainer of this repo is open to a PR from an android novice like me (:

My temporary workaround: I'm not using the `isRemoveWifiNetwork` function in my project so I've forked this repo and commented out the body to the function so it's not calling `getConfiguredNetworks` and it works fine.

**Comment by eliaslecomte** [comment]
Have you gone through the readme? https://github.com/JuanSeBestia/react-native-wifi-reborn#access_fine_location-permission

**Comment by cashc** [comment]
yes, I have followed the Android steps in the readme and have added the line
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`
to the `AndroidManifest.xml` file. The linter error still appears though. 

Idk if this matter but these are my versions: 
```
Gradle 6.0.1
------------------------------------------------------------
Build time:   2019-11-18 20:25:01 UTC

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_202-ea (Oracle Corporation 25.202-b03)
OS:           Mac OS X 10.15.4 x86_64
```

Also, I added the `ACCESS_FINE_LOCATION` permission to your react-native-wifi-reborn project manifest file and then ran `./gradlew lint` and now it throws this error that has a little more detailed description:
```
/Users/cashc/my-project/node_modules/react-native-wifi-reborn/android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java:285: Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException [MissingPermission]
          final List<WifiConfiguration> mWifiConfigList = wifi.getConfiguredNetworks();
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This makes me think it's complaining about the code in RNWifiModule.java, not the way the permissions are setup in the manifest.
> Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException
