### ISSUE TITLE
build for android issues

### ISSUE THREAD

**Issue by xralphack** [JuanSeBestia/react-native-wifi-reborn#78]
react-native version: 0.59.10

1. 

```
error: cannot find symbol public void onAvailable(@NonNull final Network network) {
^symbol: class NonNull
...
```

I have to add the following in node_modules/react-native-wifi-reborn/android/gradle.properties

```
android.useAndroidX=true
android.enableJetifier=true
```

2. 

uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in ...
so this library can not support version below 21?

**Comment by eliaslecomte** [comment]
The latest version of this library only supports React Native 60+ and Android 21+.
Android SDK 20 is Android 4.4 and was released in 2014. Are your users still using that?

**Comment by xralphack** [comment]
I have not update from 0.59.10 to 0.60+, so I may change sdk:minSdkVersion to 21.

Can you add the following lines for those don't use androidx ?

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by eliaslecomte** [comment]
You have to add those in your projects gradle.properties. They should not be part of this library.

**Comment by xralphack** [comment]
got it, thx for your help
