### ISSUE TITLE
Asking Wifi on/off Permission repeatedly

### ISSUE THREAD

**Issue by mpconstruct** [JuanSeBestia/react-native-wifi-reborn#79]
When we try to connect the ssid in Android , It will asks permission repeatedly and also It doesn't responds to the user permission selection

**Comment by eliaslecomte** [comment]
What device are you using. Could you make a movie of the behavior?

**Comment by mpconstruct** [comment]
> What device are you using. Could you make a movie of the behavior?

I am using redmi4, redmi 3s prime, redmi 7s Pro

**Comment by mieupro18** [comment]
Same issue is happening for me in Redmi note 5

**Comment by jk89gr** [comment]
Hello, same issue here. 
Device: Redmi Note 8 Pro

**Comment by Rybachello** [comment]
Hello, same issue
Devide: Redmi 5 Plus

**Comment by Shamplol** [comment]
Same issue for me on my Pocophone F1. If you go in the app settings, under "other permissions" (on MIUI) you can then set "Change Wi-Fi Connectivity" to "Accept. I wonder if there is a way to do that programmatically.

**Comment by Juanjofp** [comment]
Hello, same issue in Xiaomi mi mix 2 5G, some workaround?

Thank you in advance

**Comment by eliaslecomte** [comment]
> Same issue for me on my Pocophone F1. If you go in the app settings, under "other permissions" (on MIUI) you can then set "Change Wi-Fi Connectivity" to "Accept. I wonder if there is a way to do that programmatically.

Can you then connect successfully? I assumed it was a problem with the new Android 10 wifi api.

**Comment by Shamplol** [comment]
I've been using the library successfully despite having inconsistent behavior across different mobiles. It's been better since a recent MIUI update. I use it to connected to IoT devices (set as access points with no password) :

` const connectToWifiNetwork = async wifiNetwork => {
        await WifiManager.isRemoveWifiNetwork(wifiNetwork.SSID);

        return WifiManager.connectToProtectedSSID(wifiNetwork.SSID, '', false)
            .then(async () => {
                await WifiManager.forceWifiUsage(true);
                ...
            })
            .catch(error => {
                /** Retry connection a few times */
                if (shouldAttemptAgain()) {
                    return connectToWifiNetwork(wifiNetwork);
                } 
                ...
            }`

**Comment by Shamplol** [comment]
The problem stopped on my pocophone F1 after recent MIUI updates

**Comment by eliaslecomte** [comment]
Yes this was definitely a firmware issue. I've added code to our android dependency https://github.com/ThanosFisherman/WifiUtils so that it mitigates the loop and throws an exception `android10ImmediatelyDroppedConnection`. It's merged and should be released soon.

**Comment by stravi** [comment]
Xiaomi Redmi 6 Pro is connecting to the network but even after the connection is successful for the next ~2min it continously pops up dialog asking for permissions.
