### ISSUE TITLE
Android 10 cancel button

### ISSUE THREAD

**Issue by xralphack** [JuanSeBestia/react-native-wifi-reborn#84]
As I click cancel button on pop up dialog, connection timeout callback still invoked.

And there is no way to add handler when user click the cancel button

**Comment by eliaslecomte** [comment]
I know :-(, still have to take that up.

**Comment by xralphack** [comment]
I also opened an issue on WifiUtils.

https://github.com/ThanosFisherman/WifiUtils/issues/68

**Comment by eliaslecomte** [comment]
I will tackle it in the WifiUtils code base.

**Comment by Rapsssito** [comment]
Moved to ThanosFisherman/WifiUtils#68
