### ISSUE TITLE
Version 4.0.1 for Android 10, connectToProtectedSSID connected ok but cannot call apis

### ISSUE THREAD

**Issue by uranashel44** [JuanSeBestia/react-native-wifi-reborn#85]
Hi @JuanSeBestia , can you please check why in Android 10, latest version, I could connect to wifi name and password but can not call api

Thanks for this awesome lib.

**Comment by eliaslecomte** [comment]
Does the wifi access point has internet access?
You could try wrapping your api call with:
forceWifiUsage(true)
// api call
forceWifiUsage(false)

**Comment by uranashel44** [comment]
Thanks for fast reply.

Can I have to add this into the first of time initialize WifiManager, and only one time?

**Comment by eliaslecomte** [comment]
You can choose to do it once you are connected and then before disconnecting or wrapping it round each api call directed to the AP.

**Comment by uranashel44** [comment]
Thank. Just tried and it does not work as expected. Wifi icon in status bar has symbol 'x' <=> could not access to internet (I have tried to go to the web, but could not connected).

I try to close the app, and have to connect myself again, internet back.

Any way else, the solution above not work. @eliaslecomte ?

**Comment by uranashel44** [comment]
Ah, one thing is: my device is Xiaomi - Android 10.

**Comment by uranashel44** [comment]
@eliaslecomte , do you have another solution for this?

**Comment by eliaslecomte** [comment]
It's important to know that since Android 10, the api we use to connect with your wifi network, only allows your app to use the wifi, and not, for example the browser.

**Comment by uranashel44** [comment]
Yes. But I mean when I tried to connect to wifi with pass/ssid, the connection is not reachable (load data failed). (Its only works when I force close the app and wifi back to normal) @eliaslecomte
