### ISSUE TITLE
Multiple inconsistencies in lib behavior (Android)

### ISSUE THREAD

**Issue by dimgrav** [JuanSeBestia/react-native-wifi-reborn#87]
Tested on React Native (Android only):
* 0.59.8
* 0.60.3
* 0.62.2

We are trying to integrate this library in a production level. So far, we've stumbled upon numerous issues, that do not appear to have been resolved in version **4.1.0**.

**Xiaomi Redmi Note 8 Pro - MIUI version 11.0.3.0 (based on Android P)**

* Wifi permission request loop that breaks randomly (with or without user interaction)
* Connects to Wifi with internet connectivity, but cannot perform external API requests

**Huawei P30 Lite - EMUI version 9.1.0 (based on Android P)**

* Connects to Wifi with internet connectivity inconsistently
* Cannot connect to IOT device in the same WLAN

**Xiaomi A2 Lite - Android One (Android Q)**

* Connects to Wifi consistently, always without internet connectivity

Example usage:

```
const connect = () => {
  WifiManager.forceWifiUsage(true);
  WifiManager.connectToProtectedSSID(ssid, password, false)
    .then(() => {
      // do stuff
    })
    .catch(() => {
      // handle error
    })
    .finally(() => WifiManager.forceWifiUsage(false));
};
```
Based on the information above, can you point me to a certain direction as to what the issue may be?

**Comment by Rapsssito** [comment]
@dimgrav, looks like `forceWifiUsage()` causes some connectivity issues (see #76).
If you are using a TCP connection to communicate with your IoT devices, I recommend you [`react-native-tcp-socket`](https://github.com/Rapsssito/react-native-tcp-socket), it allows you to bind your socket to an specific interface (`ethernet`, `wifi`, `cellular`, etc.) without forcing the whole app to use the WiFi connection.

_**Disclaimer: I am the creator and mantainer of  [`react-native-tcp-socket`](https://github.com/Rapsssito/react-native-tcp-socket)**_

**Comment by eliaslecomte** [comment]
You have to connect first, then call _WifiManager.forceWifiUsage(true);_.
I think I'll add something to the readme to make this more clear.

The loop issue is actually a firmware bug, it's up to Oneplus and Xiaomi to fix that :-/.

**Comment by nitin992503** [comment]
Hello @eliaslecomte,
In I am trying to connect to wifi of esp32 from android using this library. But it keeps disconnecting. WiFi first connects then a pop appears and then WiFi disconnects and pop disappear too. This cycle keeps going on and after some time wifi connects to my home network and then a pop up appear with failue message . Do you think this is also a firnware bug ?

**Comment by eliaslecomte** [comment]
> Hello @eliaslecomte,
> In I am trying to connect to wifi of esp32 from android using this library. But it keeps disconnecting. WiFi first connects then a pop appears and then WiFi disconnects and pop disappear too. This cycle keeps going on and after some time wifi connects to my home network and then a pop up appear with failue message . Do you think this is also a firnware bug ?

What smartphone brand/model are you using?

**Comment by nitin992503** [comment]
I am using Oneplus for testing purposes

**Comment by nitin992503** [comment]
Thanks for your quick reply

**Comment by qcasey** [comment]
I think the consensus is that this is OnePlus's issue to solve, see the thread here: https://github.com/ThanosFisherman/WifiUtils/issues/63 

In the meantime, you may want to look into the OTA updates for your device, some people claim it's fixed in beta versions:

https://issuetracker.google.com/issues/143549613#comment26

I haven't tried any, since my OP7Pro is my daily

**Comment by nitin992503** [comment]
Thank you for your comment @qcasey , I have the same issue as this one https://github.com/ThanosFisherman/WifiUtils/issues/63 . The current version of oxygen OS in my phone is 10.3.4 and in the issuetracker somebody mentioned the fix in 10.5.7, this update is not yet available to me. So i guess i will just have to wait until this update is made available.

**Comment by jk89gr** [comment]
Hello @eliaslecomte ,
since this issue is still open, I though I might ask here, instead of raising a separate one.

The behavior that @dimgrav described:
> Connects to Wifi consistently, always without internet connectivity

still occurs on `4.2.0`.

Is this supposed to be fixed by now? If so, then i can only suspect that it's bad implementation from my end, so an example usage would be very much appreciated. 

>You have to connect first, then call WifiManager.forceWifiUsage(true);.
I think I'll add something to the readme to make this more clear.

**Comment by eliaslecomte** [comment]
Yes it should be fixed.

What's the code you are currently using?

`try {
  await WifiManager.connectToProtectedSSID(ssid, password, false);
  await WifiManager.forceWifiUsage(true)
} finally {
  await WifiManager.forceWifiUsage(false))
}`
