### ISSUE TITLE
`Unable to connect to` error is raised after successful connection to WiFi on iOS

### ISSUE THREAD

**Issue by Rybachello** [JuanSeBestia/react-native-wifi-reborn#89]
### Issue Description

After a successful connection to the WiFi, the `Unable to connect to` is raised on iOS.

### Steps to Reproduce

```javascript
try {
      await WifiManager.connectToProtectedSSID(
        "ssid",
        "passord",
        false
      );
    } catch (error) {
     console.warn(error)
}
```

### Environment
I ran on a real device (iPhone XR, Software Version 13.5)

```
    "react-native": "0.62.2",
    "react-native-wifi-reborn": "^4.2.0",
```

**Comment by notjulian** [comment]
Hi @Rybachello ,
check if you have added this add these entitlements:
![82553565-93fba980-9b64-11ea-93ec-be79347759cd](https://user-images.githubusercontent.com/2241601/86290735-3d1ad280-bbee-11ea-9a3f-80e06b32dffd.png)

**Comment by Rybachello** [comment]
@notjulian Yes, I have added, but still got an error.

**Comment by notjulian** [comment]
@Rybachello 
what you read on the console of xcode?
can you post it here, please?

**Comment by Rybachello** [comment]
@notjulian  I double-checked entitlements and I found that I didn't add Access Wifi Information to entitlements.
Thank you for help.

**Comment by notjulian** [comment]
@Rybachello you're welcome
