### ISSUE TITLE
Connect to device in lopping 

### ISSUE THREAD

**Issue by kilisoria** [JuanSeBestia/react-native-wifi-reborn#90]
Hi All!

I'm having an issue to connect my app against a real Android device, using the default code on the page. 

```
"react-native": "0.61.5",
"react-native-wifi-reborn": "^4.2.0",
```

```
WifiManager.connectToProtectedSSID(ssid, password, isWep).then(

  () => {
    console.log("Connected successfully!");
  },
  () => {
    console.log("Connection failed!");
  }
);
```

The problem is the device connects in loop, it shows firstly "device to use with [APP NAME] " later the "connection successful" message but the process repites in loop. My code in the app ran only one time. 

Someone has any idea regarding it? Or have it or a similar case?

Thank you in advence!

Regards,

**Comment by eliaslecomte** [comment]
This is actually a firmware bug. Pr has been merged to avoid the loop & it should be released soon.
