### ISSUE TITLE
Native module WifiManager tried to override RNWifiModule

### ISSUE THREAD

**Issue by CKitisak** [JuanSeBestia/react-native-wifi-reborn#93]
I'm using the react-native with react-native-navigation and I stuck with the error below. please suggest me how to solve it.

I have tried adding this in `MainApplication.java` but doesn't solve the problem.

```
@Override
        public boolean canOverrideExistingModule() {
          return true;
        }
```

![Screenshot_20200708-133237_CeosQuickConnect](https://user-images.githubusercontent.com/2785185/86892222-27476900-c12a-11ea-9c55-947c11dc3290.jpg)

here is my deps:
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-navigation": "^6.9.0",
"react-native-vector-icons": "^7.0.0",
"react-native-wifi-reborn": "^4.2.0"

by the way the document need to update as the import part is wrong `import com.reactlibrary.RNWifiPackage;`
the right one is `import com.reactlibrary.rnwifi.RNWifiPackage;

**Comment by eliaslecomte** [comment]
You don't have to add it, that should happen by autolinking (automatic).

**Comment by CKitisak** [comment]
@eliaslecomte thank you. it works after removed it. so I think the document of `When using Wix React Native Navigation` need to be updated or remove to not confuse anyone in the future.

**Comment by eliaslecomte** [comment]
Wix React Native Navigation fixed autolinking in their last version.
