### ISSUE TITLE
Android application crashed in connecting to a second wifi

### ISSUE THREAD

**Issue by pouyaalikhanzade** [JuanSeBestia/react-native-wifi-reborn#94]
hi for an IOT project i am connecting to an esp wifi using your package...
phone successfully gets connected to esp but after i want to connect the phone back to my own wifi application shows a toast said connection successful but application crashes and wifi gets connected and then it gets disconnected super fast my code is exacly same as documentation in both times
react-native: 0.62.2
react-native-wifi-reborn: 4.2.0

**Comment by eliaslecomte** [comment]
Instead of connecting back I would just disconnect and use [isRemoveWifiNetwork]( https://github.com/JuanSeBestia/react-native-wifi-reborn#isremovewifinetworkssid-string-promiseboolean).

Can you give more information about the error you are facing? Logs / exception.
