### ISSUE TITLE
Problem in reactNative@0.63.1

### ISSUE THREAD

**Issue by rogerespinoza** [JuanSeBestia/react-native-wifi-reborn#97]
Hi Guys, excuse me, I have the same problem, first I tried to add the dependency in an expo app, but after ejecting it, and it didn't work, then I assumed it was something related to expo, and I tried in a pure reactNative app, and I also had a problem , I don't know what else could be the problem, I have reactNative@0.63.1, please can you help me or, say if someone had a similar problem. #52

**Comment by Rapsssito** [comment]
@rogerespinoza, I am sorry you are having this issue. To avoid duplicate issues, I will remove this one and move the conversation over #52.
